
CREATE VIEW [dbo].[NounModAttrValues] WITH
   SCHEMABINDING
AS
   SELECT ATTRVAL.ATTRIBUTE, ATTRVAL.[VALUE], COUNT_BIG (*) AS COUNTS
     FROM dbo.ATTRVAL ATTRVAL
    WHERE (ATTRVAL.STATUS = 'A')
   GROUP BY ATTRIBUTE, [VALUE]
GO
CREATE UNIQUE NONCLUSTERED INDEX [NounModAttrValues_INDEX01]
    ON [dbo].[NounModAttrValues]([ATTRIBUTE] ASC, [VALUE] ASC) WITH (FILLFACTOR = 100);


GO
CREATE UNIQUE CLUSTERED INDEX [idx_Nonclustered_NounModAttrValues_ATTRIBUTE_VALUE]
    ON [dbo].[NounModAttrValues]([ATTRIBUTE] ASC, [VALUE] ASC) WITH (FILLFACTOR = 100);

