CREATE TABLE [dbo].[PACKAGE] (
    [Recnum]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [MASTER]         VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [SPRNUM]         VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [QUANTITY]       DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [DESC]           VARCHAR (36)    DEFAULT (' ') NOT NULL,
    [WHLS_PRICE]     DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [LN]             DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [DLR_PRICE]      DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [RTL_PRICE]      DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [LawEnf_Price]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [Star_Price]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [BoxStore_Price] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [BuyGroup_Price] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PACKAGE_INDEX01] PRIMARY KEY CLUSTERED ([MASTER] ASC, [LN] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PACKAGE_INDEX00]
    ON [dbo].[PACKAGE]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PACKAGE_INDEX02]
    ON [dbo].[PACKAGE]([SPRNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

