CREATE TABLE [dbo].[PRSTATAX] (
    [Recnum]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [STATE_CODE]      VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [STATE_NUM]       VARCHAR (8)    DEFAULT (' ') NOT NULL,
    [STATE_NAME]      VARCHAR (15)   DEFAULT (' ') NOT NULL,
    [STATE_DESC]      VARCHAR (30)   DEFAULT (' ') NOT NULL,
    [WITH_AMT]        DECIMAL (6)    DEFAULT ((0)) NOT NULL,
    [CALC_TYP]        DECIMAL (2)    DEFAULT ((0)) NOT NULL,
    [EX_CREDIT]       DECIMAL (4)    DEFAULT ((0)) NOT NULL,
    [REG_WTHOLD_PERC] DECIMAL (4, 2) DEFAULT ((0)) NOT NULL,
    [ADD_WTHOLD_PERC] DECIMAL (4, 2) DEFAULT ((0)) NOT NULL,
    [WORK_COMP_MAX]   DECIMAL (8, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PRSTATAX_INDEX01] PRIMARY KEY CLUSTERED ([STATE_CODE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PRSTATAX_INDEX00]
    ON [dbo].[PRSTATAX]([Recnum] ASC) WITH (FILLFACTOR = 70);

