CREATE TABLE [dbo].[WOCOST] (
    [Recnum]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [WO_#]           DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [LINE]           DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [MINUTES]        DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [DATE]           DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [SHIFT]          VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [UPDATED]        VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [QUAN]           DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [TYPE]           VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [COST]           DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [FREIGHT]        DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [UNIT_COST]      DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [VENDOR_ID]      VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [VENDOR_INVOICE] VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [PO_#]           DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [DL_RATE]        DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [IL_RATE]        DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [FO_RATE]        DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    CONSTRAINT [WOCOST_INDEX01] PRIMARY KEY CLUSTERED ([WO_#] ASC, [LINE] ASC, [TYPE] ASC, [VENDOR_ID] ASC, [DATE] ASC, [SHIFT] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOCOST_INDEX00]
    ON [dbo].[WOCOST]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOCOST_INDEX02]
    ON [dbo].[WOCOST]([DATE] ASC, [SHIFT] ASC, [WO_#] ASC, [LINE] ASC, [TYPE] ASC, [VENDOR_ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOCOST_INDEX03]
    ON [dbo].[WOCOST]([WO_#] ASC, [LINE] ASC, [Recnum] ASC);

