CREATE TABLE [dbo].[GLChkAcc] (
    [Recnum]          BIGINT       IDENTITY (1, 1) NOT NULL,
    [ID]              DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [CHECKACCT_TITLE] VARCHAR (40) DEFAULT (' ') NOT NULL,
    [CHECKACCT_NUMB]  VARCHAR (10) DEFAULT (' ') NOT NULL,
    [CHECKACCT_ROUT]  VARCHAR (10) DEFAULT (' ') NOT NULL,
    [CHECKACCT_BANK]  VARCHAR (12) DEFAULT (' ') NOT NULL,
    [LAST_CHECK#]     DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLChkAcc_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLChkAcc_INDEX00]
    ON [dbo].[GLChkAcc]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLChkAcc_INDEX02]
    ON [dbo].[GLChkAcc]([CHECKACCT_TITLE] ASC) WITH (FILLFACTOR = 70);

