CREATE TABLE [dbo].[INUOM] (
    [Recnum] BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]   VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [QTY]    DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [INUOM_INDEX01] PRIMARY KEY CLUSTERED ([CODE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INUOM_INDEX00]
    ON [dbo].[INUOM]([Recnum] ASC) WITH (FILLFACTOR = 70);

