CREATE TABLE [dbo].[APVENDEL] (
    [Recnum]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]      VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [VENDOR_#]        VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [VENDOR_NAME]     VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [VENDOR_ADDR1]    VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [VENDOR_ADDR2]    VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [VENDOR_CITY]     VARCHAR (17)    DEFAULT (' ') NOT NULL,
    [STATE]           VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ZIP]             VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [PHONE_NUMBER]    VARCHAR (13)    DEFAULT (' ') NOT NULL,
    [CONTACT]         VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [YTD_PURCHASES]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [YTD_PAYMENTS]    DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [YTD_BALANCE]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [YTD_TAX]         DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [YTD_DISCOUNT]    DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [YTD_FREIGHT]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [YTD_CREDITS]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [DATE_LAST_PAID]  DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [AMT_LAST_PAID]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [LAST_CHECK]      DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [APPLIED_CREDIT]  DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [FLAG_1099]       VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [FEDID]           VARCHAR (11)    DEFAULT (' ') NOT NULL,
    [MANUAL_CHECKNUM] DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [TERMS_TYPE]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [TERMS_DAYS]      DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [TERMS_PERCENT]   DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [VOUCHERS_PAID]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [CREDITS_TAKEN]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [DUE_DAYS]        DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [APVEN_RECNUM]    DECIMAL (14)    DEFAULT ((0)) NOT NULL,
    [YRS_OLD]         DECIMAL (6, 2)  DEFAULT ((0)) NOT NULL,
    [SING_MULTI]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [ID]              DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APCOMPAN_ID]     DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APVENDEL_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_APVENDEL_APCOMPAN_ID] FOREIGN KEY ([APCOMPAN_ID]) REFERENCES [dbo].[APCOMPAN] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APVENDEL_INDEX00]
    ON [dbo].[APVENDEL]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APVENDEL_INDEX02]
    ON [dbo].[APVENDEL]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APVENDEL_INDEX03]
    ON [dbo].[APVENDEL]([APCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

