CREATE TABLE [dbo].[FEDBATCH] (
    [Recnum]          BIGINT       IDENTITY (1, 1) NOT NULL,
    [GUNTYPE]         VARCHAR (1)  CONSTRAINT [DF__FEDBATCH__GUNTYP__774C8E8E] DEFAULT (' ') NOT NULL,
    [SERIAL]          VARCHAR (14) CONSTRAINT [DF__FEDBATCH__SERIAL__7840B2C7] DEFAULT (' ') NOT NULL,
    [RECEIVED]        DATETIME     CONSTRAINT [DF__FEDBATCH__RECEIV__7934D700] DEFAULT ('01/01/1753') NOT NULL,
    [MANUFACT]        VARCHAR (10) CONSTRAINT [DF__FEDBATCH__MANUFA__7A28FB39] DEFAULT (' ') NOT NULL,
    [MODEL]           VARCHAR (10) CONSTRAINT [DF__FEDBATCH__MODEL__7B1D1F72] DEFAULT (' ') NOT NULL,
    [SEMIFULL]        VARCHAR (1)  CONSTRAINT [DF__FEDBATCH__SEMIFU__7C1143AB] DEFAULT (' ') NOT NULL,
    [NAME]            VARCHAR (25) CONSTRAINT [DF__FEDBATCH__NAME__7D0567E4] DEFAULT (' ') NOT NULL,
    [STREET]          VARCHAR (20) CONSTRAINT [DF__FEDBATCH__STREET__7DF98C1D] DEFAULT (' ') NOT NULL,
    [CITY]            VARCHAR (15) CONSTRAINT [DF__FEDBATCH__CITY__7EEDB056] DEFAULT (' ') NOT NULL,
    [STATE]           VARCHAR (2)  CONSTRAINT [DF__FEDBATCH__STATE__7FE1D48F] DEFAULT (' ') NOT NULL,
    [SPRNUM]          VARCHAR (20) CONSTRAINT [DF__FEDBATCH__SPRNUM__00D5F8C8] DEFAULT (' ') NOT NULL,
    [PRINTED]         VARCHAR (1)  CONSTRAINT [DF__FEDBATCH__PRINTE__01CA1D01] DEFAULT (' ') NOT NULL,
    [CALIBER]         VARCHAR (10) CONSTRAINT [DF__FEDBATCH__CALIBE__02BE413A] DEFAULT (' ') NOT NULL,
    [GUNMODEL]        VARCHAR (20) CONSTRAINT [DF__FEDBATCH__GUNMOD__03B26573] DEFAULT (' ') NOT NULL,
    [LOCATION]        VARCHAR (20) CONSTRAINT [DF__FEDBATCH__LOCATI__04A689AC] DEFAULT (' ') NOT NULL,
    [PARTIAL]         VARCHAR (1)  CONSTRAINT [DF__FEDBATCH__PARTIA__059AADE5] DEFAULT (' ') NOT NULL,
    [Book]            VARCHAR (8)  NULL,
    [Country]         VARCHAR (2)  NULL,
    [Street2]         VARCHAR (20) NULL,
    [ReceivingTicket] DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [RMA]             DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [PONumber]        INT          CONSTRAINT [DF_FedBatch_PONumber] DEFAULT ((0)) NOT NULL,
    [POLine]          INT          CONSTRAINT [DF_FedBatch_POLine] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FEDBATCH_INDEX01] PRIMARY KEY CLUSTERED ([GUNTYPE] ASC, [SERIAL] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_FEDBATCH_GUNTYPE] FOREIGN KEY ([GUNTYPE]) REFERENCES [dbo].[GUNTYPES] ([CODE]),
    CONSTRAINT [FK_FEDBATCH_SPRNUM] FOREIGN KEY ([SPRNUM]) REFERENCES [dbo].[parts] ([SPRNUM])
);






GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBATCH_INDEX00]
    ON [dbo].[FEDBATCH]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBATCH_INDEX02]
    ON [dbo].[FEDBATCH]([GUNTYPE] ASC, [SPRNUM] ASC, [NAME] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBATCH_INDEX03]
    ON [dbo].[FEDBATCH]([SPRNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBATCH_INDEX04]
    ON [dbo].[FEDBATCH]([GUNTYPE] ASC, [SERIAL] ASC, [LOCATION] ASC) WITH (FILLFACTOR = 70);

