CREATE TABLE [dbo].[WOLOCATN] (
    [Recnum]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [NUM]             VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [DATE]            DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DIR_RATE]        DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [INDIR_RATE]      DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [OVERHEAD_RATE]   DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [DEPT_NAME]       VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [DIVISION_ID]     VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [ACCOUNT_ID]      VARCHAR (5)     DEFAULT (' ') NOT NULL,
    [MAN_HRS_PER_DAY] DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [NUM_WORKERS]     DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [NUM_SHIFTS]      DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [RPT_HRS_PER_DAY] DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [RPT_DAYS]        DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [RPT_FLAG]        VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [OLD_DL_RATE]     DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [OLD_IL_RATE]     DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [OLD_FO_RATE]     DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    CONSTRAINT [WOLOCATN_INDEX01] PRIMARY KEY CLUSTERED ([NUM] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOLOCATN_INDEX00]
    ON [dbo].[WOLOCATN]([Recnum] ASC) WITH (FILLFACTOR = 70);

