CREATE TABLE [dbo].[APAUGLD] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]   VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]  VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [VENDOR_#]    VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [INVOICE_#]   VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [VOUCH_FLAG]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [LINE_#]      DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [COMP_#]      VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIV_#]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DEPT_#]      VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ACCOUNT_#]   VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [AMOUNT]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [ID]          DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APVENDOR_ID] DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APAUTOVO_ID] DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLXREF_ID]   DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APAUGLD_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [INVOICE_#] ASC, [VOUCH_FLAG] ASC, [LINE_#] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_APAUGLD_APAUTOVO_ID] FOREIGN KEY ([APAUTOVO_ID]) REFERENCES [dbo].[APAUTOVO] ([ID]),
    CONSTRAINT [FK_APAUGLD_GLXREF_ID] FOREIGN KEY ([GLXREF_ID]) REFERENCES [dbo].[GLXREF] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APAUGLD_INDEX00]
    ON [dbo].[APAUGLD]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APAUGLD_INDEX02]
    ON [dbo].[APAUGLD]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APAUGLD_INDEX03]
    ON [dbo].[APAUGLD]([APVENDOR_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APAUGLD_INDEX04]
    ON [dbo].[APAUGLD]([APAUTOVO_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APAUGLD_INDEX05]
    ON [dbo].[APAUGLD]([GLXREF_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

