CREATE TABLE [dbo].[YARDPRIC] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [ID]            DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [YARDCODE]      VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [SPRNUM]        VARCHAR (20)    NOT NULL,
    [PRICE]         DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [ORDER_COMMENT] VARCHAR (MAX)   NULL,
    CONSTRAINT [YARDPRIC_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_YARDPRIC_SPRNUM] FOREIGN KEY ([SPRNUM]) REFERENCES [dbo].[parts] ([SPRNUM]),
    CONSTRAINT [FK_YARDPRIC_YARDCODE] FOREIGN KEY ([YARDCODE]) REFERENCES [dbo].[YardCode] ([YARDCODE])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [YARDPRIC_INDEX00]
    ON [dbo].[YARDPRIC]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [YARDPRIC_INDEX02]
    ON [dbo].[YARDPRIC]([YARDCODE] ASC, [SPRNUM] ASC);

