CREATE TABLE [dbo].[fedbkold] (
    [Recnum]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [GUNTYPE]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SERIAL]    VARCHAR (14)    DEFAULT (' ') NOT NULL,
    [RECEIVED]  DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [MANUFACT]  VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [MODEL]     VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [SEMIFULL]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [NAME]      VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [STREET]    VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [CITY]      VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [STATE]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [SPRNUM]    VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [GUNMODEL]  VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [SOLD]      DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [SONAME]    VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [SOSTREET]  VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [SOCITY]    VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [SOSTATE]   VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [SOLDFFL]   VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [ORDNUM]    DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [TAG]       VARCHAR (6)     DEFAULT (' ') NOT NULL,
    [SAFETY]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [GUNSMITH]  VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [TAGNUM]    DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [FEDCODE]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [CALIBER]   VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [WO_NUMBER] DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [COMMENT]   VARCHAR (20)    DEFAULT (' ') NOT NULL,
    CONSTRAINT [fedbkold_INDEX01] PRIMARY KEY CLUSTERED ([GUNTYPE] ASC, [SERIAL] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fedbkold_INDEX00]
    ON [dbo].[fedbkold]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fedbkold_INDEX02]
    ON [dbo].[fedbkold]([ORDNUM] ASC, [GUNTYPE] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fedbkold_INDEX03]
    ON [dbo].[fedbkold]([TAGNUM] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fedbkold_INDEX05]
    ON [dbo].[fedbkold]([SONAME] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fedbkold_INDEX06]
    ON [dbo].[fedbkold]([SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fedbkold_INDEX07]
    ON [dbo].[fedbkold]([GUNTYPE] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fedbkold_INDEX08]
    ON [dbo].[fedbkold]([SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [fedbkold_INDEX11]
    ON [dbo].[fedbkold]([NAME] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

