CREATE TABLE [dbo].[ARStatmt] (
    [Recnum]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [USER]     VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [ORDNUM]   DECIMAL (10, 2) NOT NULL,
    [ORDTOTAL] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [BALDUE]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [HIST_RF]  DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [DAYS]     DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [CUSTID]   VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [INTEREST] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ARStatmt_INDEX01] PRIMARY KEY CLUSTERED ([USER] ASC, [CUSTID] ASC, [DAYS] ASC, [ORDNUM] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARStatmt_INDEX00]
    ON [dbo].[ARStatmt]([Recnum] ASC) WITH (FILLFACTOR = 70);

