CREATE TABLE [dbo].[SysAcct] (
    [Recnum]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [GLBatch]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLCompan]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLChkAcc]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLDisWrk]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLDiv]         DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLDX]          DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLFunct]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLJourn]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLMaster]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLRBatch]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLReport]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLRptFmt]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLRptMst]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLRTrans]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLSort]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLTrans]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLType]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLUSer]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLWork]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLXRef]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLRet]         DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APAutovo]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APAugld]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APCash]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APCheck]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APChkud]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APCompan]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APGLWork]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APLedger]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APManchk]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APPaid]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APPerled]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APPerm]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APRecon]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APVendel]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APVendor]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APVouche]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [APWork]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [PRGLxfer]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARCrdHst]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARCrDtl]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARCrHdr]       DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARCrHHst]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARDtlHst]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARHeader]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARHeadhs]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARSlsTax]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARTaxHst]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARWork]        DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [ARDetail]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [Payor]         DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [OESaleTax]     DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [TaxDiffLimit]  NUMERIC (6, 2) NULL,
    [FreezeRoot]    VARCHAR (100)  NULL,
    [SQLBackupPath] VARCHAR (100)  NULL,
    [SQLDBPath]     VARCHAR (100)  NULL,
    [SQLLogPath]    VARCHAR (100)  NULL,
    CONSTRAINT [SysAcct_INDEX00] PRIMARY KEY CLUSTERED ([Recnum] ASC) WITH (FILLFACTOR = 70)
);

