CREATE TABLE [dbo].[FEDBKSAV] (
    [Recnum]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [GUNTYPE]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SERIAL]    VARCHAR (14)    DEFAULT (' ') NOT NULL,
    [RECEIVED]  DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [MANUFACT]  VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [MODEL]     VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [SEMIFULL]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [NAME]      VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [STREET]    VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [CITY]      VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [STATE]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [SPRNUM]    VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [GUNMODEL]  VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [SOLD]      DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [SONAME]    VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [SOSTREET]  VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [SOCITY]    VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [SOSTATE]   VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [SOLDFFL]   VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [ORDNUM]    DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [TAG]       VARCHAR (6)     DEFAULT (' ') NOT NULL,
    [SAFETY]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [GUNSMITH]  VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [TAGNUM]    DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [FEDCODE]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [CALIBER]   VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [WO_NUMBER] DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [COMMENT]   VARCHAR (20)    DEFAULT (' ') NOT NULL,
    CONSTRAINT [FEDBKSAV_INDEX01] PRIMARY KEY CLUSTERED ([GUNTYPE] ASC, [SERIAL] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_FEDBKSAV_FEDCODE] FOREIGN KEY ([FEDCODE]) REFERENCES [dbo].[FEDCODE] ([GROUP_CODE]),
    CONSTRAINT [FK_FEDBKSAV_GUNTYPE] FOREIGN KEY ([GUNTYPE]) REFERENCES [dbo].[GUNTYPES] ([CODE])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKSAV_INDEX00]
    ON [dbo].[FEDBKSAV]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKSAV_INDEX02]
    ON [dbo].[FEDBKSAV]([ORDNUM] ASC, [GUNTYPE] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKSAV_INDEX03]
    ON [dbo].[FEDBKSAV]([TAGNUM] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKSAV_INDEX04]
    ON [dbo].[FEDBKSAV]([SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKSAV_INDEX05]
    ON [dbo].[FEDBKSAV]([SONAME] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKSAV_INDEX07]
    ON [dbo].[FEDBKSAV]([GUNTYPE] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKSAV_INDEX10]
    ON [dbo].[FEDBKSAV]([SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKSAV_INDEX11]
    ON [dbo].[FEDBKSAV]([NAME] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

