CREATE TABLE [dbo].[wotimsub] (
    [Recnum]     BIGINT       IDENTITY (1, 1) NOT NULL,
    [RECORD_REL] DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [WO_#]       DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [LINE]       DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [MINUTES]    DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [QUAN]       DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [EMP_ID]     VARCHAR (10) DEFAULT (' ') NOT NULL,
    [FLAG]       VARCHAR (1)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [wotimsub_INDEX01] PRIMARY KEY CLUSTERED ([RECORD_REL] ASC, [WO_#] ASC, [LINE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [wotimsub_INDEX00]
    ON [dbo].[wotimsub]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [wotimsub_INDEX02]
    ON [dbo].[wotimsub]([WO_#] ASC, [LINE] ASC, [RECORD_REL] ASC) WITH (FILLFACTOR = 70);

