CREATE TABLE [dbo].[subref] (
    [Recnum]       BIGINT       IDENTITY (1, 1) NOT NULL,
    [MASTPART]     VARCHAR (20) DEFAULT (' ') NOT NULL,
    [SUBPART]      VARCHAR (20) DEFAULT (' ') NOT NULL,
    [AMOUNT]       DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [INV_STATE]    VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [REPLACE_FLAG] VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [CreatedBy]    VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [CreatedDate]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]    VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [ChangedDate]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [Version]      VARCHAR (15) DEFAULT (' ') NOT NULL,
    [TaxQty]       INT          NULL,
    CONSTRAINT [subref_INDEX01] PRIMARY KEY CLUSTERED ([MASTPART] ASC, [SUBPART] ASC) WITH (FILLFACTOR = 70)
);


GO
ALTER TABLE [dbo].[subref] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);




GO
CREATE UNIQUE NONCLUSTERED INDEX [subref_INDEX00]
    ON [dbo].[subref]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [subref_INDEX02]
    ON [dbo].[subref]([SUBPART] ASC, [MASTPART] ASC) WITH (FILLFACTOR = 70);

