CREATE TABLE [dbo].[PRACECOD] (
    [Recnum]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [RACE_CODE]      VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DESCRIPTN]      VARCHAR (25) DEFAULT (' ') NOT NULL,
    [CLASSIFICATION] VARCHAR (15) DEFAULT (' ') NOT NULL,
    [MINORITY]       VARCHAR (1)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [PRACECOD_INDEX01] PRIMARY KEY CLUSTERED ([RACE_CODE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PRACECOD_INDEX00]
    ON [dbo].[PRACECOD]([Recnum] ASC) WITH (FILLFACTOR = 70);

