CREATE TABLE [dbo].[ARWORK] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [BILL_TO]     VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [BILL_NAME]   VARCHAR (36)    DEFAULT (' ') NOT NULL,
    [B_ACCTYPE]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SHIP_TO]     VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [SHIP_NAME]   VARCHAR (36)    DEFAULT (' ') NOT NULL,
    [S_ACCTYPE]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [FROM_PROG]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [GEN_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ORDNUM]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [ORD_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [SHIP_DATE]   DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [COM]         VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SUBTOTAL]    DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [DISCOUNT]    DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [POSTAGE]     DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [DEPOSIT]     DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [COD]         DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [TAX]         DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [ORD_TOTAL]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [RECEIVED_TD] DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [STILL_DUE]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [ORD_STATUS]  VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [CARD_TYPE]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [ID]          DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ARWORK_INDEX01] PRIMARY KEY CLUSTERED ([BILL_NAME] ASC, [SHIP_DATE] ASC, [ORDNUM] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARWORK_INDEX00]
    ON [dbo].[ARWORK]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARWORK_INDEX02]
    ON [dbo].[ARWORK]([SHIP_NAME] ASC, [SHIP_DATE] ASC, [ORDNUM] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARWORK_INDEX03]
    ON [dbo].[ARWORK]([SHIP_DATE] ASC, [ORDNUM] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARWORK_INDEX04]
    ON [dbo].[ARWORK]([ORDNUM] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARWORK_INDEX05]
    ON [dbo].[ARWORK]([ORD_DATE] ASC, [ORDNUM] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARWORK_INDEX06]
    ON [dbo].[ARWORK]([ID] ASC) WITH (FILLFACTOR = 70);

