CREATE TABLE [dbo].[WONOTE] (
    [Recnum]    BIGINT       IDENTITY (1, 1) NOT NULL,
    [WO_#]      DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [WO_LINE]   DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [LINE]      DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [NOTE_CODE] VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [DESC]      VARCHAR (30) DEFAULT (' ') NOT NULL,
    CONSTRAINT [WONOTE_INDEX01] PRIMARY KEY CLUSTERED ([WO_#] ASC, [WO_LINE] ASC, [LINE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WONOTE_INDEX00]
    ON [dbo].[WONOTE]([Recnum] ASC) WITH (FILLFACTOR = 70);

