CREATE TABLE [dbo].[SYSINVEN] (
    [Recnum]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [SPRNUM]         VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [WOPO_FLAG]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [NUMBER]         DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [RELEASE_#]      DECIMAL (8)     NOT NULL,
    [DATE]           DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [FIN]            DECIMAL (14)    DEFAULT ((0)) NOT NULL,
    [RAW]            DECIMAL (14)    DEFAULT ((0)) NOT NULL,
    [UCOST]          DECIMAL (12, 6) DEFAULT ((0)) NOT NULL,
    [RAW_UCOST]      DECIMAL (12, 6) DEFAULT ((0)) NOT NULL,
    [TCOST]          DECIMAL (20, 6) DEFAULT ((0)) NOT NULL,
    [RAW_TCOST]      DECIMAL (20, 6) DEFAULT ((0)) NOT NULL,
    [FREIGHT]        DECIMAL (10, 6) DEFAULT ((0)) NOT NULL,
    [RAW_FREIGHT]    DECIMAL (10, 6) DEFAULT ((0)) NOT NULL,
    [COST_FLAG]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [RESERVED]       DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [ON_ORDER]       DECIMAL (14)    DEFAULT ((0)) NOT NULL,
    [PROJECTED_DATE] DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ORIG_DATE]      DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [STD_UCOST]      DECIMAL (12, 6) DEFAULT ((0)) NOT NULL,
    [RAW_STD_UCOST]  DECIMAL (12, 6) DEFAULT ((0)) NOT NULL,
    [CreatedBy]      VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [CreatedDate]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]      VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [ChangedDate]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [Version]        VARCHAR (15)    DEFAULT (' ') NOT NULL,
    CONSTRAINT [SYSINVEN_INDEX01] PRIMARY KEY CLUSTERED ([SPRNUM] ASC, [WOPO_FLAG] ASC, [NUMBER] ASC, [RELEASE_#] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SYSINVEN_INDEX00]
    ON [dbo].[SYSINVEN]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SYSINVEN_INDEX02]
    ON [dbo].[SYSINVEN]([SPRNUM] ASC, [DATE] ASC, [WOPO_FLAG] ASC, [NUMBER] ASC, [RELEASE_#] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SYSINVEN_INDEX03]
    ON [dbo].[SYSINVEN]([SPRNUM] ASC, [PROJECTED_DATE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SYSINVEN_INDEX04]
    ON [dbo].[SYSINVEN]([WOPO_FLAG] ASC, [SPRNUM] ASC, [NUMBER] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SYSINVEN_INDEX05]
    ON [dbo].[SYSINVEN]([SPRNUM] ASC, [WOPO_FLAG] ASC, [NUMBER] ASC, [DATE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

