CREATE TABLE [dbo].[PartsLog] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [OPTION]        DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [SPRNUM]        VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [AMOUNT]        DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [ENTDATE]       DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [TAGNUM]        VARCHAR (6)     DEFAULT (' ') NOT NULL,
    [NOTES]         VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [UNUSED]        DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [WO_NUMBER]     DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [INV_STATUS]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [GL_ACCT_#]     VARCHAR (9)     DEFAULT (' ') NOT NULL,
    [DEFECT_COST]   DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [LINE]          DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [SER_COUNT]     DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [AUTOENTRY]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [OPERATOR]      VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [TO_STATUS]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [NOTETEXT]      VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [TIME]          DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [DEFECT_TAG]    DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [OPER_1]        VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [OPER_2]        VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [OPER_3]        VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [DEFECT_SOURCE] VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [FREIGHT_COST]  DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [WOPO_FLAG]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    CONSTRAINT [PartsLog_INDEX01] PRIMARY KEY CLUSTERED ([SPRNUM] ASC, [DEFECT_TAG] ASC, [LINE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PartsLog_INDEX00]
    ON [dbo].[PartsLog]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PartsLog_INDEX02]
    ON [dbo].[PartsLog]([TAGNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PartsLog_INDEX03]
    ON [dbo].[PartsLog]([DEFECT_TAG] ASC, [LINE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PartsLog_INDEX04]
    ON [dbo].[PartsLog]([NOTES] ASC, [SPRNUM] ASC, [DEFECT_TAG] ASC, [LINE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PartsLog_INDEX05]
    ON [dbo].[PartsLog]([ENTDATE] ASC, [TIME] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PartsLog_INDEX06]
    ON [dbo].[PartsLog]([SPRNUM] ASC, [ENTDATE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PartsLog_INDEX07]
    ON [dbo].[PartsLog]([OPTION] ASC, [SPRNUM] ASC, [ENTDATE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

