CREATE TABLE [dbo].[FedBkCmP] (
    [RECNUM]        BIGINT       IDENTITY (1, 1) NOT NULL,
    [GUNTYPE]       VARCHAR (1)  NOT NULL,
    [SERIAL]        VARCHAR (14) NOT NULL,
    [RECEIVED]      DATETIME     NOT NULL,
    [MANUFACT]      VARCHAR (10) NULL,
    [MODEL]         VARCHAR (10) NULL,
    [SEMIFULL]      VARCHAR (1)  NULL,
    [NAME]          VARCHAR (25) NOT NULL,
    [STREET]        VARCHAR (20) NULL,
    [CITY]          VARCHAR (15) NULL,
    [STATE]         VARCHAR (2)  NULL,
    [SPRNUM]        VARCHAR (20) NOT NULL,
    [Overall1]      VARCHAR (1)  NULL,
    [GUNMODEL]      VARCHAR (20) CONSTRAINT [DF_FedBkCmP_GUNMODEL] DEFAULT (' ') NOT NULL,
    [SOLD]          DATETIME     NOT NULL,
    [SONAME]        VARCHAR (25) NOT NULL,
    [SOSTREET]      VARCHAR (35) NULL,
    [SOCITY]        VARCHAR (15) NULL,
    [SOSTATE]       VARCHAR (2)  NULL,
    [SOLDFFL]       VARCHAR (8)  NOT NULL,
    [ORDNUM]        INT          NULL,
    [TAG]           VARCHAR (6)  NULL,
    [SAFETY]        VARCHAR (1)  NULL,
    [GUNSMITH]      VARCHAR (6)  CONSTRAINT [DF_FedBkCmP_GUNSMITH] DEFAULT (' ') NOT NULL,
    [TAGNUM]        INT          NULL,
    [FEDCODE]       VARCHAR (1)  NULL,
    [CALIBER]       VARCHAR (4)  CONSTRAINT [DF_FedBkCmP_CALIBER] DEFAULT (' ') NOT NULL,
    [WO_NUMBER]     INT          NULL,
    [COMMENT]       VARCHAR (6)  NULL,
    [RCTICKET]      INT          NULL,
    [BAN_STATUS]    VARCHAR (1)  NULL,
    [LOCATION]      VARCHAR (20) NULL,
    [CHANGE_FLAG]   VARCHAR (1)  NULL,
    [INITIALS]      VARCHAR (10) NULL,
    [NOTES]         VARCHAR (60) CONSTRAINT [DF_FedBkCmP_NOTES] DEFAULT (' ') NOT NULL,
    [MANUFFL]       VARCHAR (23) NOT NULL,
    [XferDate]      DATETIME     NOT NULL,
    [SoldReceived]  VARCHAR (1)  NOT NULL,
    [AIMImportDate] DATETIME     NOT NULL,
    [Year]          SMALLINT     NOT NULL,
    [SerialNS]      VARCHAR (14) NOT NULL,
    CONSTRAINT [FedBkCmP_INDEX00] PRIMARY KEY CLUSTERED ([RECNUM] ASC) WITH (FILLFACTOR = 70)
);






GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX01]
    ON [dbo].[FedBkCmP]([GUNTYPE] ASC, [SERIAL] ASC, [RECEIVED] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX02]
    ON [dbo].[FedBkCmP]([SOLDFFL] ASC, [GUNTYPE] ASC, [SPRNUM] ASC, [SERIAL] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX03]
    ON [dbo].[FedBkCmP]([GUNSMITH] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX04]
    ON [dbo].[FedBkCmP]([CALIBER] ASC, [SPRNUM] ASC, [SERIAL] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX05]
    ON [dbo].[FedBkCmP]([GUNMODEL] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX06]
    ON [dbo].[FedBkCmP]([SPRNUM] ASC, [SERIAL] ASC, [RECNUM] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX07]
    ON [dbo].[FedBkCmP]([GUNTYPE] ASC, [RECEIVED] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX08]
    ON [dbo].[FedBkCmP]([SERIAL] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX11]
    ON [dbo].[FedBkCmP]([NAME] ASC, [SERIAL] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX12]
    ON [dbo].[FedBkCmP]([NOTES] ASC, [SERIAL] ASC, [RECNUM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkCmP_INDEX13]
    ON [dbo].[FedBkCmP]([AIMImportDate] ASC, [Year] ASC, [GUNTYPE] ASC, [RECNUM] ASC);


GO


