CREATE TABLE [dbo].[WOTimErr] (
    [Recnum]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [WO_#]        DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [LINE]        DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [DATE]        DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [DATE_IN]     DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [HRS_IN]      VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [MIN_IN]      VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DATEOUT]     DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [HRS_OUT]     VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [MIN_OUT]     VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [EMP_ID]      VARCHAR (10) DEFAULT (' ') NOT NULL,
    [SHIFT]       VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [SHOP_FLAG]   VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [ERROR_#]     DECIMAL (2)  DEFAULT ((0)) NOT NULL,
    [ERR_MESSAGE] VARCHAR (40) DEFAULT (' ') NOT NULL,
    CONSTRAINT [WOTimErr_INDEX01] PRIMARY KEY CLUSTERED ([SHOP_FLAG] ASC, [DATE] ASC, [SHIFT] ASC, [EMP_ID] ASC, [ERROR_#] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimErr_INDEX00]
    ON [dbo].[WOTimErr]([Recnum] ASC) WITH (FILLFACTOR = 70);

