CREATE TABLE [dbo].[RCHEADER] (
    [Recnum]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [TICKET]         DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [RECEIVE_DATE]   DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [RECEIVE_TYPE]   VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [RECEIVE_NUMBER] DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [RECEIVE_ID]     VARCHAR (10) DEFAULT (' ') NOT NULL,
    [NAME]           VARCHAR (35) DEFAULT (' ') NOT NULL,
    [STREET]         VARCHAR (35) DEFAULT (' ') NOT NULL,
    [CITY]           VARCHAR (20) DEFAULT (' ') NOT NULL,
    [STATE]          VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [ZIP]            VARCHAR (10) DEFAULT (' ') NOT NULL,
    [UPDATE_FLAG]    VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [LAST_LINE]      DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [ENTERED_BY]     VARCHAR (10) DEFAULT (' ') NOT NULL,
    [UPDATED_BY]     VARCHAR (10) DEFAULT (' ') NOT NULL,
    [ORDER_BY]       VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [UPDATE_DATE]    DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [CreatedBy]      VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [CreatedDate]    DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]      VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [ChangedDate]    DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [Version]        VARCHAR (15) DEFAULT (' ') NOT NULL,
    CONSTRAINT [RCHEADER_INDEX01] PRIMARY KEY CLUSTERED ([TICKET] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RCHEADER_INDEX00]
    ON [dbo].[RCHEADER]([Recnum] ASC) WITH (FILLFACTOR = 70);

