CREATE TABLE [dbo].[FEDBKXDB] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [GUNTYPE]     VARCHAR (1)     CONSTRAINT [DF__FEDBKXDB__GUNTYP__6F76629C] DEFAULT (' ') NOT NULL,
    [SERIAL]      VARCHAR (14)    CONSTRAINT [DF__FEDBKXDB__SERIAL__706A86D5] DEFAULT (' ') NOT NULL,
    [RECEIVED]    DATETIME        CONSTRAINT [DF__FEDBKXDB__RECEIV__715EAB0E] DEFAULT ('01/01/1753') NOT NULL,
    [MANUFACT]    VARCHAR (10)    CONSTRAINT [DF__FEDBKXDB__MANUFA__7252CF47] DEFAULT (' ') NOT NULL,
    [MODEL]       VARCHAR (10)    CONSTRAINT [DF__FEDBKXDB__MODEL__7346F380] DEFAULT (' ') NOT NULL,
    [SEMIFULL]    VARCHAR (1)     CONSTRAINT [DF__FEDBKXDB__SEMIFU__743B17B9] DEFAULT (' ') NOT NULL,
    [NAME]        VARCHAR (25)    CONSTRAINT [DF__FEDBKXDB__NAME__752F3BF2] DEFAULT (' ') NOT NULL,
    [STREET]      VARCHAR (20)    CONSTRAINT [DF__FEDBKXDB__STREET__7623602B] DEFAULT (' ') NOT NULL,
    [CITY]        VARCHAR (15)    CONSTRAINT [DF__FEDBKXDB__CITY__77178464] DEFAULT (' ') NOT NULL,
    [STATE]       VARCHAR (2)     CONSTRAINT [DF__FEDBKXDB__STATE__780BA89D] DEFAULT (' ') NOT NULL,
    [SPRNUM]      VARCHAR (20)    CONSTRAINT [DF__FEDBKXDB__SPRNUM__78FFCCD6] DEFAULT (' ') NOT NULL,
    [GUNMODEL]    VARCHAR (20)    CONSTRAINT [DF__FEDBKXDB__GUNMOD__79F3F10F] DEFAULT (' ') NOT NULL,
    [SOLD]        DATETIME        CONSTRAINT [DF__FEDBKXDB__SOLD__7AE81548] DEFAULT ('01/01/1753') NOT NULL,
    [SONAME]      VARCHAR (25)    CONSTRAINT [DF__FEDBKXDB__SONAME__7BDC3981] DEFAULT (' ') NOT NULL,
    [SOSTREET]    VARCHAR (35)    CONSTRAINT [DF__FEDBKXDB__SOSTRE__7CD05DBA] DEFAULT (' ') NOT NULL,
    [SOCITY]      VARCHAR (15)    CONSTRAINT [DF__FEDBKXDB__SOCITY__7DC481F3] DEFAULT (' ') NOT NULL,
    [SOSTATE]     VARCHAR (2)     CONSTRAINT [DF__FEDBKXDB__SOSTAT__7EB8A62C] DEFAULT (' ') NOT NULL,
    [SOLDFFL]     VARCHAR (10)    CONSTRAINT [DF__FEDBKXDB__SOLDFF__7FACCA65] DEFAULT (' ') NOT NULL,
    [ORDNUM]      DECIMAL (10, 2) CONSTRAINT [DF__FEDBKXDB__ORDNUM__00A0EE9E] DEFAULT ((0)) NOT NULL,
    [TAG]         VARCHAR (6)     CONSTRAINT [DF__FEDBKXDB__TAG__019512D7] DEFAULT (' ') NOT NULL,
    [SAFETY]      VARCHAR (1)     CONSTRAINT [DF__FEDBKXDB__SAFETY__02893710] DEFAULT (' ') NOT NULL,
    [GUNSMITH]    VARCHAR (10)    CONSTRAINT [DF__FEDBKXDB__GUNSMI__037D5B49] DEFAULT (' ') NOT NULL,
    [TAGNUM]      DECIMAL (6)     CONSTRAINT [DF__FEDBKXDB__TAGNUM__04717F82] DEFAULT ((0)) NOT NULL,
    [FEDCODE]     VARCHAR (1)     CONSTRAINT [DF__FEDBKXDB__FEDCOD__0565A3BB] DEFAULT (' ') NOT NULL,
    [CALIBER]     VARCHAR (10)    CONSTRAINT [DF__FEDBKXDB__CALIBE__0659C7F4] DEFAULT (' ') NOT NULL,
    [WO_NUMBER]   DECIMAL (6)     CONSTRAINT [DF__FEDBKXDB__WO_NUM__074DEC2D] DEFAULT ((0)) NOT NULL,
    [COMMENT]     VARCHAR (20)    CONSTRAINT [DF__FEDBKXDB__COMMEN__08421066] DEFAULT (' ') NOT NULL,
    [RCTICKET]    DECIMAL (6)     CONSTRAINT [DF__FEDBKXDB__RCTICK__0936349F] DEFAULT ((0)) NOT NULL,
    [BAN_STATUS]  VARCHAR (1)     CONSTRAINT [DF__FEDBKXDB__BAN_ST__0A2A58D8] DEFAULT (' ') NOT NULL,
    [LOCATION]    VARCHAR (20)    CONSTRAINT [DF__FEDBKXDB__LOCATI__0B1E7D11] DEFAULT (' ') NOT NULL,
    [CHANGE_FLAG] VARCHAR (1)     CONSTRAINT [DF__FEDBKXDB__CHANGE__0C12A14A] DEFAULT (' ') NOT NULL,
    [INITIALS]    VARCHAR (10)    CONSTRAINT [DF__FEDBKXDB__INITIA__0D06C583] DEFAULT (' ') NOT NULL,
    [MANUFFL]     VARCHAR (20)    CONSTRAINT [DF__FEDBKXDB__MANUFF__0DFAE9BC] DEFAULT (' ') NOT NULL,
    [CreatedBy]   VARCHAR (4)     CONSTRAINT [DF__FEDBKXDB__Create__0EEF0DF5] DEFAULT (' ') NOT NULL,
    [CreatedDate] DATETIME        CONSTRAINT [DF__FEDBKXDB__Create__0FE3322E] DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]   VARCHAR (4)     CONSTRAINT [DF__FEDBKXDB__Change__10D75667] DEFAULT (' ') NOT NULL,
    [ChangedDate] DATETIME        CONSTRAINT [DF__FEDBKXDB__Change__11CB7AA0] DEFAULT ('01/01/1753') NOT NULL,
    [Version]     VARCHAR (15)    CONSTRAINT [DF__FEDBKXDB__Versio__12BF9ED9] DEFAULT (' ') NOT NULL,
    CONSTRAINT [FEDBKXDB_INDEX01] PRIMARY KEY CLUSTERED ([GUNTYPE] ASC, [SERIAL] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_FEDBKXDB_FEDCODE] FOREIGN KEY ([FEDCODE]) REFERENCES [dbo].[FEDCODE] ([GROUP_CODE]),
    CONSTRAINT [FK_FEDBKXDB_SPRNUM] FOREIGN KEY ([SPRNUM]) REFERENCES [dbo].[parts] ([SPRNUM])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKXDB_INDEX00]
    ON [dbo].[FEDBKXDB]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKXDB_INDEX02]
    ON [dbo].[FEDBKXDB]([ORDNUM] ASC, [GUNTYPE] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKXDB_INDEX03]
    ON [dbo].[FEDBKXDB]([TAGNUM] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKXDB_INDEX04]
    ON [dbo].[FEDBKXDB]([RCTICKET] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKXDB_INDEX05]
    ON [dbo].[FEDBKXDB]([SONAME] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKXDB_INDEX06]
    ON [dbo].[FEDBKXDB]([SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKXDB_INDEX07]
    ON [dbo].[FEDBKXDB]([GUNTYPE] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKXDB_INDEX08]
    ON [dbo].[FEDBKXDB]([SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

