CREATE TABLE [dbo].[WOXREF] (
    [Recnum]    BIGINT       IDENTITY (1, 1) NOT NULL,
    [SPRNUM]    VARCHAR (20) DEFAULT (' ') NOT NULL,
    [WOPO_FLAG] VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [NUMBER]    DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [RELEASE_#] DECIMAL (8)  NOT NULL,
    [WONUM_TO]  DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [QUAN]      DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [INV_STATE] VARCHAR (1)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [WOXREF_INDEX01] PRIMARY KEY CLUSTERED ([SPRNUM] ASC, [WOPO_FLAG] ASC, [NUMBER] ASC, [RELEASE_#] ASC, [WONUM_TO] ASC)
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [WOXREF_INDEX00]
    ON [dbo].[WOXREF]([Recnum] ASC) ;
GO

CREATE UNIQUE NONCLUSTERED INDEX [WOXREF_INDEX02]
    ON [dbo].[WOXREF]([WONUM_TO] ASC, [SPRNUM] ASC, [WOPO_FLAG] ASC, [NUMBER] ASC, [RELEASE_#] ASC) ;

