CREATE TABLE [dbo].[APMANCHK] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]    VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [CHECK_NO]      DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [CHECK_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [CHECK_TOTAL]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [LINE_#]        DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [DIVID]         VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [VENDOR_#]      VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [VENDOR_NAME]   VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [VENDOR_ADDR1]  VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [VENDOR_ADDR2]  VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [VENDOR_CITY]   VARCHAR (17)    DEFAULT (' ') NOT NULL,
    [STATE]         VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ZIP]           VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [TOPRINT_FLAG]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PRINTED_FLAG]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [EDIT_FLAG]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [CASH_FLAG]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [DISTRIBUTIONS] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [REFERENCE]     VARCHAR (13)    DEFAULT (' ') NOT NULL,
    [INVOICE_#]     VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [UPDATE]        VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [ID]            DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APVENDOR_ID]   DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APCOMPAN_ID]   DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APMANCHK_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [CHECK_NO] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APMANCHK_INDEX00]
    ON [dbo].[APMANCHK]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APMANCHK_INDEX02]
    ON [dbo].[APMANCHK]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APMANCHK_INDEX03]
    ON [dbo].[APMANCHK]([APVENDOR_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APMANCHK_INDEX04]
    ON [dbo].[APMANCHK]([APCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

