CREATE TABLE [dbo].[WOTimDtl] (
    [Recnum]          BIGINT       IDENTITY (1, 1) NOT NULL,
    [WO_#]            DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [LINE]            DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [DATE]            DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [UPDATED]         VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [DATE_IN]         DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [HRS_IN]          VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [MIN_IN]          VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DATE_OUT]        DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [HRS_OUT]         VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [MIN_OUT]         VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [EMP_ID]          VARCHAR (10) DEFAULT (' ') NOT NULL,
    [TIME]            VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [PASSWD]          VARCHAR (8)  DEFAULT (' ') NOT NULL,
    [MINUTES]         DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [QUAN]            DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [SHIFT]           VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [QUAN_UPDTE_FLAG] VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [OPERATION]       VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [LOCATION]        VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [MACHINE]         VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [SHOP_FLAG]       VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [PR_UPDATE_FLAG]  VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [ID]              DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [PASSWDIN]        VARCHAR (8)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [WOTimDtl_INDEX01] PRIMARY KEY CLUSTERED ([EMP_ID] ASC, [DATE] ASC, [WO_#] ASC, [LINE] ASC, [HRS_IN] ASC, [MIN_IN] ASC, [TIME] ASC)
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX00]
    ON [dbo].[WOTimDtl]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX02]
    ON [dbo].[WOTimDtl]([EMP_ID] ASC, [DATE] ASC, [TIME] ASC, [HRS_IN] ASC, [MIN_IN] ASC, [WO_#] ASC, [LINE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX03]
    ON [dbo].[WOTimDtl]([DATE] ASC, [SHIFT] ASC, [EMP_ID] ASC, [TIME] ASC, [HRS_IN] ASC, [MIN_IN] ASC, [WO_#] ASC, [LINE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX04]
    ON [dbo].[WOTimDtl]([WO_#] ASC, [LINE] ASC, [DATE] ASC, [EMP_ID] ASC, [TIME] ASC, [HRS_IN] ASC, [MIN_IN] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX05]
    ON [dbo].[WOTimDtl]([WO_#] ASC, [LINE] ASC, [UPDATED] ASC, [Recnum] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX06]
    ON [dbo].[WOTimDtl]([OPERATION] ASC, [DATE] ASC, [SHIFT] ASC, [Recnum] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX07]
    ON [dbo].[WOTimDtl]([DATE] ASC, [SHIFT] ASC, [EMP_ID] ASC, [LOCATION] ASC, [Recnum] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX08]
    ON [dbo].[WOTimDtl]([SHOP_FLAG] ASC, [DATE] ASC, [SHIFT] ASC, [EMP_ID] ASC, [DATE_IN] ASC, [HRS_IN] ASC, [WO_#] ASC, [LINE] ASC, [Recnum] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX09]
    ON [dbo].[WOTimDtl]([ID] ASC, [Recnum] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTimDtl_INDEX10]
    ON [dbo].[WOTimDtl]([EMP_ID] ASC, [DATE] ASC, [DATE_IN] ASC, [HRS_IN] ASC, [MIN_IN] ASC, [ID] ASC);

