CREATE TABLE [dbo].[INVMNOTE] (
    [Recnum]     BIGINT       IDENTITY (1, 1) NOT NULL,
    [ID]         VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [TEXT]       VARCHAR (30) DEFAULT (' ') NOT NULL,
    [STATUS]     VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [COSTFLAG]   VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [ENTFLAG]    VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [UNDO_FLAG]  DECIMAL (2)  DEFAULT ((0)) NOT NULL,
    [PRINT_FLAG] VARCHAR (1)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [INVMNOTE_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INVMNOTE_INDEX00]
    ON [dbo].[INVMNOTE]([Recnum] ASC) WITH (FILLFACTOR = 70);

