CREATE TABLE [dbo].[PLFinish] (
    [Recnum]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [ID]          DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [FINISH]      VARCHAR (20) DEFAULT (' ') NOT NULL,
    [Description] VARCHAR (60) DEFAULT (' ') NOT NULL,
    CONSTRAINT [PLFinish_INDEX01] PRIMARY KEY CLUSTERED ([FINISH] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PLFinish_INDEX00]
    ON [dbo].[PLFinish]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PLFinish_INDEX02]
    ON [dbo].[PLFinish]([ID] ASC) WITH (FILLFACTOR = 70);

