CREATE TABLE [dbo].[ARDETAIL] (
    [PAYMENT_#]   DECIMAL (8)     CONSTRAINT [DF__ARDETAIL__PAYMEN__02B35442] DEFAULT ((0)) NOT NULL,
    [ORDNUM]      DECIMAL (10, 2) CONSTRAINT [DF__ARDETAIL__ORDNUM__03A7787B] DEFAULT ((0)) NOT NULL,
    [BCUSTID]     VARCHAR (10)    CONSTRAINT [DF__ARDETAIL__BCUSTI__049B9CB4] DEFAULT (' ') NOT NULL,
    [AMOUNT]      DECIMAL (10, 2) CONSTRAINT [DF__ARDETAIL__AMOUNT__058FC0ED] DEFAULT ((0)) NOT NULL,
    [DISCOUNT]    DECIMAL (10, 2) CONSTRAINT [DF__ARDETAIL__DISCOU__0683E526] DEFAULT ((0)) NOT NULL,
    [UPDATED]     VARCHAR (1)     CONSTRAINT [DF__ARDETAIL__UPDATE__0778095F] DEFAULT (' ') NOT NULL,
    [BATCH_#]     DECIMAL (4)     CONSTRAINT [DF__ARDETAIL__BATCH___086C2D98] DEFAULT ((0)) NOT NULL,
    [ID]          BIGINT          IDENTITY (1390224, 1) NOT NULL,
    [ARHEADER_ID] DECIMAL (10)    CONSTRAINT [DF__ARDETAIL__ARHEAD__0A54760A] DEFAULT ((0)) NOT NULL,
    [BNAME]       VARCHAR (40)    CONSTRAINT [DF__ARDETAIL__BNAME__0B489A43] DEFAULT (' ') NOT NULL,
    [DATE]        DATETIME        CONSTRAINT [DF__ARDETAIL__DATE__0C3CBE7C] DEFAULT ('01/01/1753') NOT NULL,
    [InvoiceNum]  DECIMAL (8)     CONSTRAINT [DF__ARDETAIL__Invoic__0D30E2B5] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ARDETAIL_INDEX05] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ARDETAIL_ARHEADER_ID] FOREIGN KEY ([ARHEADER_ID]) REFERENCES [dbo].[ARHEADER] ([ID])
);








GO



GO
CREATE UNIQUE NONCLUSTERED INDEX [ARDETAIL_INDEX02]
    ON [dbo].[ARDETAIL]([UPDATED] ASC, [PAYMENT_#] ASC, [ORDNUM] ASC, [ID] ASC);






GO
CREATE UNIQUE NONCLUSTERED INDEX [ARDETAIL_INDEX03]
    ON [dbo].[ARDETAIL]([ORDNUM] ASC, [PAYMENT_#] ASC, [ID] ASC);






GO
CREATE UNIQUE NONCLUSTERED INDEX [ARDETAIL_INDEX04]
    ON [dbo].[ARDETAIL]([BCUSTID] ASC, [ORDNUM] ASC, [PAYMENT_#] ASC, [ID] ASC);






GO
CREATE UNIQUE NONCLUSTERED INDEX [ARDETAIL_INDEX06]
    ON [dbo].[ARDETAIL]([ARHEADER_ID] ASC, [ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARDETAIL_INDEX07]
    ON [dbo].[ARDETAIL]([DATE] ASC, [BCUSTID] ASC, [PAYMENT_#] ASC, [ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARDETAIL_INDEX08]
    ON [dbo].[ARDETAIL]([InvoiceNum] ASC, [ORDNUM] ASC, [PAYMENT_#] ASC, [ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARDETAIL_INDEX09]
    ON [dbo].[ARDETAIL]([PAYMENT_#] ASC, [ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARDETAIL_INDEX01]
    ON [dbo].[ARDETAIL]([PAYMENT_#] ASC, [ORDNUM] ASC, [ID] ASC);

