CREATE TABLE [dbo].[APVOUCHE] (
    [Recnum]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]      VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [VENDOR_#]        VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [INVOICE_#]       VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [VOUCH_FLAG]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [VOUCHER_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DUE_DATE]        DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [INVOICE_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [AMOUNT_DUE]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [FREIGHT]         DECIMAL (6, 2)  DEFAULT ((0)) NOT NULL,
    [TAX]             DECIMAL (6, 2)  DEFAULT ((0)) NOT NULL,
    [DISCOUNT_AMOUNT] DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [DISC_DATE]       DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DISC_PERCENT]    DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [DISCOUNT_FLAG]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [REFERENCE]       VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [EDIT_FLAG]       VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [ID]              DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APVENDOR_ID]     DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [DOLLDIST]        DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [LAST_LINE#]      DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APVOUCHE_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [INVOICE_#] ASC, [VOUCH_FLAG] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_APVOUCHE_APVENDOR_ID] FOREIGN KEY ([APVENDOR_ID]) REFERENCES [dbo].[APVENDOR] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APVOUCHE_INDEX00]
    ON [dbo].[APVOUCHE]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APVOUCHE_INDEX02]
    ON [dbo].[APVOUCHE]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APVOUCHE_INDEX03]
    ON [dbo].[APVOUCHE]([APVENDOR_ID] ASC, [INVOICE_#] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

