CREATE TABLE [dbo].[TAGOPERS] (
    [Recnum] BIGINT      IDENTITY (1, 1) NOT NULL,
    [CODE]   VARCHAR (4) DEFAULT (' ') NOT NULL,
    [BATCH]  DECIMAL (4) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [TAGOPERS_INDEX01] PRIMARY KEY CLUSTERED ([CODE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TAGOPERS_INDEX00]
    ON [dbo].[TAGOPERS]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TAGOPERS_INDEX02]
    ON [dbo].[TAGOPERS]([BATCH] ASC, [CODE] ASC) WITH (FILLFACTOR = 70);

