CREATE TABLE [dbo].[TAGWORK] (
    [Recnum]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [TAG]            DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [SPRNUM]         VARCHAR (20) DEFAULT (' ') NOT NULL,
    [STAT]           VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [QUAN]           DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [OPER]           VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [BATCH]          DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [CHECKED]        VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [UPDATED]        VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [TagCheckedBy]   VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [TagCheckedDate] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [TagUpdatedBy]   VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [TagUpdatedDate] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    CONSTRAINT [TAGWORK_INDEX01] PRIMARY KEY CLUSTERED ([TAG] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TAGWORK_INDEX00]
    ON [dbo].[TAGWORK]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TAGWORK_INDEX02]
    ON [dbo].[TAGWORK]([SPRNUM] ASC, [STAT] ASC, [TAG] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TAGWORK_INDEX03]
    ON [dbo].[TAGWORK]([OPER] ASC, [BATCH] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

