CREATE TABLE [dbo].[GLFUNCT] (
    [Recnum]        BIGINT       IDENTITY (1, 1) NOT NULL,
    [FUNCTION_ID]   VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [FUNCTION_DESC] VARCHAR (40) DEFAULT (' ') NOT NULL,
    [COMMENT_1]     VARCHAR (40) DEFAULT (' ') NOT NULL,
    [COMMENT_2]     VARCHAR (40) DEFAULT (' ') NOT NULL,
    [ID]            DECIMAL (10) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLFUNCT_INDEX01] PRIMARY KEY CLUSTERED ([FUNCTION_ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLFUNCT_INDEX00]
    ON [dbo].[GLFUNCT]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLFUNCT_INDEX02]
    ON [dbo].[GLFUNCT]([ID] ASC) WITH (FILLFACTOR = 70);

