CREATE TABLE [dbo].[NOUNMOD] (
    [ID]         INT           IDENTITY (17002, 1) NOT NULL,
    [NOUN]       VARCHAR (20)  NOT NULL,
    [MODIFIER]   VARCHAR (30)  NOT NULL,
    [IMAGE]      VARCHAR (20)  NULL,
    [ABV]        VARCHAR (20)  NULL,
    [TOTAL_ATTR] SMALLINT      NULL,
    [DEFINITION] VARCHAR (MAX) NULL,
    [GUIDELINES] VARCHAR (MAX) NULL,
    [STATUS]     CHAR (1)      NULL,
    CONSTRAINT [PK__NOUNMOD__3214EC279E6BACB4] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NOUNMOD003]
    ON [dbo].[NOUNMOD]([NOUN] ASC, [MODIFIER] ASC) WITH (FILLFACTOR = 100);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NOUNMOD002]
    ON [dbo].[NOUNMOD]([NOUN] ASC, [MODIFIER] ASC) WITH (FILLFACTOR = 100);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NOUNMOD001_PK]
    ON [dbo].[NOUNMOD]([ID] ASC) WITH (FILLFACTOR = 100);

