CREATE TABLE [dbo].[APCOMPAN] (
    [Recnum]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]      VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DEPARTMENT_#]    VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [COMPANY_NAME]    VARCHAR (40)    DEFAULT (' ') NOT NULL,
    [DATE]            DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ADDR1]           VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [ADDR2]           VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [CITY]            VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [STATE]           VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ZIP]             VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [CHECKNUM]        DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [CREDITS_TAKEN]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [TOTAL_PAYMENTS]  DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [CASH_DIV]        VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [CASH_DEPT]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [CASH_ACCOUNT]    VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [A_P_DIV]         VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [A_P_DEPT]        VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [A_P_ACCOUNT]     VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [DISC_DIV]        VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DISC_DEPT]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DISC_ACCOUNT]    VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [AGE_DATE]        DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [LAST_PER_CLOSED] DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [FEDID]           VARCHAR (11)    DEFAULT (' ') NOT NULL,
    [STATEID]         VARCHAR (11)    DEFAULT (' ') NOT NULL,
    [LAST_CLOSE_DATE] DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [PO_NUMBER]       DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [MANCHECKNUM]     DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [AUTO_UPDATE]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [ID]              DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APCOMPAN_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [DEPARTMENT_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APCOMPAN_INDEX00]
    ON [dbo].[APCOMPAN]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APCOMPAN_INDEX02]
    ON [dbo].[APCOMPAN]([ID] ASC) WITH (FILLFACTOR = 70);

