CREATE TABLE [dbo].[TMPATTR] (
    [ID]            INT           IDENTITY (81323, 1) NOT NULL,
    [NMOD_ID]       INT           NOT NULL,
    [NOUN]          VARCHAR (20)  NOT NULL,
    [MODIFIER]      VARCHAR (30)  NOT NULL,
    [POS]           SMALLINT      NOT NULL,
    [ATTRIBUTE]     VARCHAR (30)  NOT NULL,
    [REQ]           CHAR (1)      NULL,
    [CK]            CHAR (1)      NULL,
    [DPOS]          SMALLINT      NULL,
    [ABV]           VARCHAR (30)  NULL,
    [PREFIX_SUFFIX] CHAR (1)      NULL,
    [SPACE]         CHAR (1)      NULL,
    [DEFINITION]    VARCHAR (MAX) NULL,
    [STATUS]        CHAR (1)      NULL,
    CONSTRAINT [TMPATTR001_PK] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TMPATTR003]
    ON [dbo].[TMPATTR]([NOUN] ASC, [MODIFIER] ASC, [ATTRIBUTE] ASC) WITH (FILLFACTOR = 100);


GO
CREATE UNIQUE NONCLUSTERED INDEX [TMPATTR002]
    ON [dbo].[TMPATTR]([NMOD_ID] ASC, [POS] ASC) WITH (FILLFACTOR = 100);

