CREATE TABLE [dbo].[PLSys] (
    [Recnum]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [Barrel_ID]          DECIMAL (10)   CONSTRAINT [DF__PLSys__Barrel_ID__1E272FE4] DEFAULT ((0)) NOT NULL,
    [Category_ID]        DECIMAL (10)   CONSTRAINT [DF__PLSys__Category___1F1B541D] DEFAULT ((0)) NOT NULL,
    [Finish_ID]          DECIMAL (10)   CONSTRAINT [DF__PLSys__Finish_ID__200F7856] DEFAULT ((0)) NOT NULL,
    [Caliber_ID]         DECIMAL (10)   CONSTRAINT [DF__PLSys__Caliber_I__21039C8F] DEFAULT ((0)) NOT NULL,
    [Part_ID]            DECIMAL (10)   CONSTRAINT [DF__PLSys__Part_ID__21F7C0C8] DEFAULT ((0)) NOT NULL,
    [Model_ID]           DECIMAL (10)   CONSTRAINT [DF__PLSys__Model_ID__22EBE501] DEFAULT ((0)) NOT NULL,
    [Test_ID]            DECIMAL (10)   CONSTRAINT [DF__PLSys__Test_ID__23E0093A] DEFAULT ((0)) NOT NULL,
    [Change_ID]          DECIMAL (10)   CONSTRAINT [DF__PLSys__Change_ID__24D42D73] DEFAULT ((0)) NOT NULL,
    [Dealer_1911]        DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Dealer_19__25C851AC] DEFAULT ((0)) NOT NULL,
    [Dealer_M1A]         DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Dealer_M1__26BC75E5] DEFAULT ((0)) NOT NULL,
    [Dealer_XD]          DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Dealer_XD__27B09A1E] DEFAULT ((0)) NOT NULL,
    [Dealer_XDM]         DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Dealer_XD__28A4BE57] DEFAULT ((0)) NOT NULL,
    [Retail_1911]        DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Retail_19__2998E290] DEFAULT ((0)) NOT NULL,
    [Retail_M1A]         DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Retail_M1__2A8D06C9] DEFAULT ((0)) NOT NULL,
    [Retail_XD]          DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Retail_XD__2B812B02] DEFAULT ((0)) NOT NULL,
    [Retail_XDM]         DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Retail_XD__2C754F3B] DEFAULT ((0)) NOT NULL,
    [Effective_Date]     DATETIME       CONSTRAINT [DF__PLSys__Effective__2D697374] DEFAULT ('01/01/1753') NOT NULL,
    [Star]               DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Star__2E5D97AD] DEFAULT ((0)) NOT NULL,
    [Buy_Group]          DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Buy_Group__2F51BBE6] DEFAULT ((0)) NOT NULL,
    [Box_Store]          DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Box_Store__3045E01F] DEFAULT ((0)) NOT NULL,
    [On_Loan]            DECIMAL (6, 4) CONSTRAINT [DF__PLSys__On_Loan__313A0458] DEFAULT ((0)) NOT NULL,
    [ProStaff]           DECIMAL (6, 4) CONSTRAINT [DF__PLSys__ProStaff__322E2891] DEFAULT ((0)) NOT NULL,
    [Range]              DECIMAL (6, 4) CONSTRAINT [DF__PLSys__Range__33224CCA] DEFAULT ((0)) NOT NULL,
    [FET_Pistol]         DECIMAL (8, 6) CONSTRAINT [DF__PLSys__FET_Pisto__34167103] DEFAULT ((0)) NOT NULL,
    [FET_Rifle]          DECIMAL (8, 6) CONSTRAINT [DF__PLSys__FET_Rifle__350A953C] DEFAULT ((0)) NOT NULL,
    [TestEffective_Date] DATETIME       NULL,
    CONSTRAINT [PLSys_INDEX00] PRIMARY KEY CLUSTERED ([Recnum] ASC) WITH (FILLFACTOR = 70)
);

