CREATE TABLE [dbo].[GLCOMPAN] (
    [Recnum]          BIGINT       IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]       VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DIVISION_#]      VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DEPARTMENT_#]    VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [NAME]            VARCHAR (30) DEFAULT (' ') NOT NULL,
    [DATE]            DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PERIOD_#]        DECIMAL (2)  DEFAULT ((0)) NOT NULL,
    [BATCH_#]         DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [NUMB_OF_PERIODS] DECIMAL (2)  DEFAULT ((0)) NOT NULL,
    [PER_1_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_1_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_2_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_2_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_3_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_3_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_4_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_4_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_5_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_5_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_6_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_6_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_7_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_7_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_8_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_8_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_9_BEG_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_9_END_DATE]  DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_10_BEG_DATE] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_10_END_DATE] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_11_BEG_DATE] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_11_END_DATE] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_12_BEG_DATE] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_12_END_DATE] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_13_BEG_DATE] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PER_13_END_DATE] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [RECUR_BATCH#]    DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [UPDATE_FLAG]     VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [ID]              DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [YEAR_CURRENT]    DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [PERIOD_CURRENT]  DECIMAL (2)  DEFAULT ((0)) NOT NULL,
    [NEXT_POST#]      DECIMAL (10) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLCOMPAN_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [DEPARTMENT_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLCOMPAN_INDEX00]
    ON [dbo].[GLCOMPAN]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLCOMPAN_INDEX02]
    ON [dbo].[GLCOMPAN]([ID] ASC) WITH (FILLFACTOR = 70);

