CREATE TABLE [dbo].[SACOMPAN] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]     VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [COMPANY_NAME]  VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [ADDR1]         VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [ADDR2]         VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [CITY]          VARCHAR (17)    DEFAULT (' ') NOT NULL,
    [STATE]         VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ZIP]           VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [UPS_SHIPPER_#] VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [NEXT_ORDNUM]   DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [NEXT_PONUM]    DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [MANIF#]        VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [PHONE_AREA]    VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [PHONE_EXCH]    VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [PHONE_NUMB]    VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [FAX_AREA]      VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [FAX_EXCH]      VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [FAX_NUMB]      VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [STATEID]       VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [DIST_TAX_FLAG] VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PS_TAX_FLAG]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    CONSTRAINT [SACOMPAN_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SACOMPAN_INDEX00]
    ON [dbo].[SACOMPAN]([Recnum] ASC) WITH (FILLFACTOR = 70);

