CREATE TABLE [dbo].[Reports] (
    [Recnum]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [ID]         DECIMAL (8)   DEFAULT ((0)) NOT NULL,
    [CATEGORY]   VARCHAR (10)  DEFAULT (' ') NOT NULL,
    [RNAME]      VARCHAR (200) DEFAULT (' ') NOT NULL,
    [DESC]       VARCHAR (200) DEFAULT (' ') NOT NULL,
    [NOTES]      VARCHAR (MAX) NULL,
    [RVActivate] VARCHAR (50)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [Reports_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [Reports_INDEX00]
    ON [dbo].[Reports]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [Reports_INDEX02]
    ON [dbo].[Reports]([CATEGORY] ASC, [DESC] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [Reports_INDEX03]
    ON [dbo].[Reports]([DESC] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [Reports_INDEX04]
    ON [dbo].[Reports]([RNAME] ASC, [CATEGORY] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

