CREATE TABLE [dbo].[ARHEADER] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [PAYMENT_#]     DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [PAYOR_ID]      VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [PAYMENT_TYPE]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PAY_INFO]      VARCHAR (30)    CONSTRAINT [DF__ARHEADER__PAY_IN__12E9BC0B] DEFAULT (' ') NOT NULL,
    [EXP_DATE]      VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [APPROVAL_#]    VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [AMOUNT]        DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [DATE]          DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [CHECK_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DEP_DATE]      DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [UPDATED]       VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [BATCH_#]       DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [TRANSFER_FLAG] VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [TRNSFR_FLAG]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [TRNSFR_ORDER]  DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [CID]           VARCHAR (5)     DEFAULT (' ') NOT NULL,
    [ID]            DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [DISCOUNT]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [TOTAL_REC]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [BNAME]         VARCHAR (40)    DEFAULT (' ') NOT NULL,
    [CheckedAmt]    NUMERIC (10, 2) NULL,
    CONSTRAINT [ARHEADER_INDEX01] PRIMARY KEY CLUSTERED ([PAYMENT_#] ASC) WITH (FILLFACTOR = 70)
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [ARHEADER_INDEX00]
    ON [dbo].[ARHEADER]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARHEADER_INDEX02]
    ON [dbo].[ARHEADER]([UPDATED] ASC, [PAYMENT_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARHEADER_INDEX03]
    ON [dbo].[ARHEADER]([UPDATED] ASC, [PAYMENT_TYPE] ASC, [PAYOR_ID] ASC, [PAYMENT_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARHEADER_INDEX04]
    ON [dbo].[ARHEADER]([DEP_DATE] ASC, [PAYMENT_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARHEADER_INDEX05]
    ON [dbo].[ARHEADER]([PAYOR_ID] ASC, [PAYMENT_#] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARHEADER_INDEX06]
    ON [dbo].[ARHEADER]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARHEADER_INDEX07]
    ON [dbo].[ARHEADER]([PAY_INFO] ASC, [PAYMENT_#] ASC);

