CREATE TABLE [dbo].[APLEDGER] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]    VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [VENDOR_#]      VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [INVOICE_#]     VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [VOUCH_FLAG]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [LINE_#]        DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [COMP_#]        VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIV_#]         VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DEPT_#]        VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ACCOUNT_#]     VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [AMOUNT]        DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [PO_#]          DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [PO_LINE_#]     DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [COST_CLOSE]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [QTY]           DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [DESCRIPTION]   VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [ID]            DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLXREF_ID]     DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APVOUCHER_ID]  DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APCOMPAN_ID]   DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [DIVACCT]       VARCHAR (7)     DEFAULT (' ') NOT NULL,
    [EventCategory] BIGINT          CONSTRAINT [DF_APLEDGER_EventCategory] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [APLEDGER_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [INVOICE_#] ASC, [VOUCH_FLAG] ASC, [LINE_#] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_APLEDGER_APVOUCHER_ID] FOREIGN KEY ([APVOUCHER_ID]) REFERENCES [dbo].[APVOUCHE] ([ID]),
    CONSTRAINT [FK_APLEDGER_GLXREF_ID] FOREIGN KEY ([GLXREF_ID]) REFERENCES [dbo].[GLXREF] ([ID])
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [APLEDGER_INDEX00]
    ON [dbo].[APLEDGER]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APLEDGER_INDEX02]
    ON [dbo].[APLEDGER]([COMP_#] ASC, [DIV_#] ASC, [DEPT_#] ASC, [ACCOUNT_#] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APLEDGER_INDEX03]
    ON [dbo].[APLEDGER]([PO_#] ASC, [PO_LINE_#] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APLEDGER_INDEX04]
    ON [dbo].[APLEDGER]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APLEDGER_INDEX05]
    ON [dbo].[APLEDGER]([GLXREF_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APLEDGER_INDEX06]
    ON [dbo].[APLEDGER]([APVOUCHER_ID] ASC, [LINE_#] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APLEDGER_INDEX07]
    ON [dbo].[APLEDGER]([APCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO



GO



GO



GO



