CREATE TABLE [dbo].[RFWORK] (
    [Recnum]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [ORDNUM]           DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [AMOUNT]           DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [CHECKNUM]         DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [CHKDTE]           DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [CRMEMO_#]         DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [PAYMENT_#]        DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [Signature1]       VARCHAR (10)    DEFAULT ('') NOT NULL,
    [Signature2]       VARCHAR (10)    DEFAULT ('') NOT NULL,
    [InvoiceNum]       DECIMAL (10, 2) NULL,
    [CHECK_CREATED_BY] VARCHAR (10)    DEFAULT ('') NOT NULL,
    CONSTRAINT [RFWORK_INDEX01] PRIMARY KEY CLUSTERED ([ORDNUM] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_RFWORK_ORDNUM] FOREIGN KEY ([ORDNUM]) REFERENCES [dbo].[CUSTINFO] ([ORDNUM])
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [RFWORK_INDEX00]
    ON [dbo].[RFWORK]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RFWORK_INDEX02]
    ON [dbo].[RFWORK]([CRMEMO_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RFWORK_INDEX03]
    ON [dbo].[RFWORK]([PAYMENT_#] ASC, [ORDNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

