CREATE TABLE [dbo].[GLRBATCH] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]    VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [BATCH_#]       DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [BATCH_TYPE]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [DEBITS]        DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [CREDITS]       DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [BALANCE]       DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [TRN_LN#]       DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [POSTED_DATE]   DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [POSTED_PERIOD] DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [POSTED_YEAR]   DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [POSTED_FLAG]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [ID]            DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLCOMPAN_ID]   DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLRBATCH_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [BATCH_#] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_GLRBATCH_GLCOMPAN_ID] FOREIGN KEY ([GLCOMPAN_ID]) REFERENCES [dbo].[GLCOMPAN] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRBATCH_INDEX00]
    ON [dbo].[GLRBATCH]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRBATCH_INDEX02]
    ON [dbo].[GLRBATCH]([COMPANY_#] ASC, [BATCH_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRBATCH_INDEX03]
    ON [dbo].[GLRBATCH]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRBATCH_INDEX04]
    ON [dbo].[GLRBATCH]([GLCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

