CREATE TABLE [dbo].[APPerm] (
    [Recnum]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]        VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [VENDOR_#]         VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [INVOICE_#]        VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [VOUCH_FLAG]       VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [VOUCHER_DATE]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DUE_DATE]         DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [INVOICE_DATE]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [AMOUNT_DUE]       DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [FREIGHT]          DECIMAL (6, 2)  DEFAULT ((0)) NOT NULL,
    [TAX]              DECIMAL (6, 2)  DEFAULT ((0)) NOT NULL,
    [DISCOUNT_AMOUNT]  DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [DISC_DATE]        DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DISC_PERCENT]     DECIMAL (8, 4)  DEFAULT ((0)) NOT NULL,
    [DISCOUNT_FLAG]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [REFERENCE]        VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [DISCOUNT_TAKEN]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PAID_FLAG]        VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PART_PAYMENTS]    DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [MANUAL_CHECKS]    DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [PRINT_FLAG]       VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PAY_FLAG]         VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [ORIG_AMOUNT]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [EOM_FLAG]         VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PAID_DATE]        DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [CHECKNUM]         DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [PARTIAL_COUNTER]  DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [CASH_FLAG]        VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [MANCHECKS]        DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [MANUAL_FLAG]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [VENDOR_NAME]      VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [ID]               DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APVENDOR_ID]      DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APCOMPAN_ID]      DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APMANCHK_ID]      DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [VOID_FLAG]        VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SIGNATURE_1]      VARCHAR (10)    NULL,
    [SIGNATURE_2]      VARCHAR (10)    NULL,
    [CHECK_CREATED_BY] VARCHAR (10)    NULL,
    CONSTRAINT [APPerm_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [INVOICE_#] ASC, [VOUCH_FLAG] ASC) WITH (FILLFACTOR = 70)
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX00]
    ON [dbo].[APPerm]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX02]
    ON [dbo].[APPerm]([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [MANCHECKS] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX03]
    ON [dbo].[APPerm]([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [MANCHECKS] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX04]
    ON [dbo].[APPerm]([CHECKNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX05]
    ON [dbo].[APPerm]([PAID_DATE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX06]
    ON [dbo].[APPerm]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX07]
    ON [dbo].[APPerm]([APVENDOR_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX08]
    ON [dbo].[APPerm]([APCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX09]
    ON [dbo].[APPerm]([APMANCHK_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX10]
    ON [dbo].[APPerm]([COMPANY_#] ASC, [DIVISION_#] ASC, [PAID_FLAG] ASC, [VOID_FLAG] ASC, [VENDOR_#] ASC, [INVOICE_#] ASC, [ID] ASC);

