CREATE TABLE [dbo].[GLSORT] (
    [Recnum]     BIGINT       IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]  VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DIVISION_#] VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [BATCH_#]    DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [ID]         DECIMAL (10) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLSORT_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [BATCH_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLSORT_INDEX00]
    ON [dbo].[GLSORT]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLSORT_INDEX02]
    ON [dbo].[GLSORT]([ID] ASC) WITH (FILLFACTOR = 70);

