CREATE TABLE [dbo].[WODetail] (
    [Recnum]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [WO_#]            DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [LINE]            DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [LOCATION]        VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [MACHINE]         VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [OPERATION]       VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [OPER_TYPE]       VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [NUMNOTES]        DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [QUAN]            DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [MACH_TIME]       DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [STD_TIME]        DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [STD_MATERIAL]    DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [STD_SUBCONTRACT] DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [UNIT_MEAS]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ACTIVE_FLAG]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [STD_LABOR]       DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [STD_INDIRECT]    DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [STD_OVERHEAD]    DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [ACT_TIME]        DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [ACT_MATERIAL]    DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [ACT_SUBCONTRACT] DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [ACT_LABOR]       DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [ACT_INDIRECT]    DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [ACT_OVERHEAD]    DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [COMPLETE_QUAN]   DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [PIECES_PER_HOUR] DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [CreatedBy]       VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [CreatedDate]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]       VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [ChangedDate]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [Version]         VARCHAR (15)    DEFAULT (' ') NOT NULL,
    CONSTRAINT [WODetail_INDEX01] PRIMARY KEY CLUSTERED ([WO_#] ASC, [LINE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WODetail_INDEX00]
    ON [dbo].[WODetail]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WODetail_INDEX02]
    ON [dbo].[WODetail]([LOCATION] ASC, [WO_#] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WODetail_INDEX03]
    ON [dbo].[WODetail]([MACHINE] ASC, [WO_#] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WODetail_INDEX04]
    ON [dbo].[WODetail]([OPERATION] ASC, [WO_#] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WODetail_INDEX05]
    ON [dbo].[WODetail]([WO_#] ASC, [LINE] ASC);

