CREATE TABLE [dbo].[GLRTRANS] (
    [Recnum]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]      VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DEPARTMENT_#]   VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ACCOUNT_#]      VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [BATCH_#]        DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [LINE_#]         DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [BATCH_TYPE]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SOURCE]         VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [TRANS_DATE]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DEBIT_AMOUNT]   DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [CREDIT_AMOUNT]  DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [POSTED_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [POSTED_PERIOD]  DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [POSTED_YEAR]    DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [POSTED_FLAG]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [REFERENCE_DESC] VARCHAR (45)    DEFAULT (' ') NOT NULL,
    [ID]             DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLMASTER_ID]    DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLRBATCH_ID]    DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLJOURN_ID]     DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [DIVACCT]        VARCHAR (5)     DEFAULT (' ') NOT NULL,
    CONSTRAINT [GLRTRANS_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [DEPARTMENT_#] ASC, [ACCOUNT_#] ASC, [ID] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_GLRTRANS_GLMASTER_ID] FOREIGN KEY ([GLMASTER_ID]) REFERENCES [dbo].[GLMASTER] ([ID]),
    CONSTRAINT [FK_GLRTRANS_GLRBATCH_ID] FOREIGN KEY ([GLRBATCH_ID]) REFERENCES [dbo].[GLRBATCH] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRTRANS_INDEX00]
    ON [dbo].[GLRTRANS]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRTRANS_INDEX02]
    ON [dbo].[GLRTRANS]([COMPANY_#] ASC, [BATCH_#] ASC, [LINE_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRTRANS_INDEX03]
    ON [dbo].[GLRTRANS]([COMPANY_#] ASC, [DIVISION_#] ASC, [BATCH_#] ASC, [LINE_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRTRANS_INDEX04]
    ON [dbo].[GLRTRANS]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRTRANS_INDEX05]
    ON [dbo].[GLRTRANS]([GLMASTER_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRTRANS_INDEX06]
    ON [dbo].[GLRTRANS]([GLRBATCH_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRTRANS_INDEX07]
    ON [dbo].[GLRTRANS]([GLJOURN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

