CREATE TABLE [dbo].[ARCRDTL] (
    [Recnum]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [CRMEMO_#]   DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [LINE_#]     DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [SPRNUM]     VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [DESC]       VARCHAR (35)    DEFAULT (' ') NOT NULL,
    [QTY]        DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [UNITPR]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [ID]         DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [ARCRHDR_ID] DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [AMOUNT]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ARCRDTL_INDEX01] PRIMARY KEY CLUSTERED ([CRMEMO_#] ASC, [LINE_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRDTL_INDEX00]
    ON [dbo].[ARCRDTL]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRDTL_INDEX02]
    ON [dbo].[ARCRDTL]([SPRNUM] ASC, [CRMEMO_#] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRDTL_INDEX03]
    ON [dbo].[ARCRDTL]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRDTL_INDEX04]
    ON [dbo].[ARCRDTL]([ARCRHDR_ID] ASC, [LINE_#] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

