CREATE TABLE [dbo].[RFNote] (
    [RFNoteID] DECIMAL (14)  IDENTITY (1, 1) NOT NULL,
    [CHECKNUM] DECIMAL (6)   DEFAULT ((0)) NOT NULL,
    [Note]     VARCHAR (256) NULL,
    CONSTRAINT [RFNote_INDEX01] PRIMARY KEY CLUSTERED ([CHECKNUM] ASC)
);

