CREATE TABLE [dbo].[PRCOMPAN] (
    [Recnum]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [COMPANY_NUMBER] VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [COMPANY_NAME]   VARCHAR (40)   DEFAULT (' ') NOT NULL,
    [DATE]           DATETIME       DEFAULT ('01/01/1753') NOT NULL,
    [CNTR_NAME]      VARCHAR (40)   DEFAULT (' ') NOT NULL,
    [PAY_PD_DATE]    DATETIME       DEFAULT ('01/01/1753') NOT NULL,
    [PAY_CK_DATE]    DATETIME       DEFAULT ('01/01/1753') NOT NULL,
    [PAY_CHK_NUMB]   DECIMAL (6)    DEFAULT ((0)) NOT NULL,
    [CURR_PAY_FREQ]  VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [PAY_FREQ_1]     VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [PAY_FREQ_2]     VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [PAY_FREQ_#1_K]  DECIMAL (2)    DEFAULT ((0)) NOT NULL,
    [PAY_FREQ_2#_K]  DECIMAL (2)    DEFAULT ((0)) NOT NULL,
    [ANNUAL_WITHLDG] DECIMAL (4)    DEFAULT ((0)) NOT NULL,
    [FICA_PCT]       DECIMAL (4, 2) DEFAULT ((0)) NOT NULL,
    [FICA_MAX]       DECIMAL (8, 2) DEFAULT ((0)) NOT NULL,
    [WEEK]           VARCHAR (1)    DEFAULT (' ') NOT NULL,
    [HRLY_FLAG]      VARCHAR (1)    DEFAULT (' ') NOT NULL,
    [SLRY_FLAG]      VARCHAR (1)    DEFAULT (' ') NOT NULL,
    [POST_FLAG]      VARCHAR (1)    DEFAULT (' ') NOT NULL,
    [W2_FLAG]        VARCHAR (1)    DEFAULT (' ') NOT NULL,
    [941_FLAG]       VARCHAR (1)    DEFAULT (' ') NOT NULL,
    [EMPLOYERS_FICA] DECIMAL (4, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PRCOMPAN_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_NUMBER] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PRCOMPAN_INDEX00]
    ON [dbo].[PRCOMPAN]([Recnum] ASC) WITH (FILLFACTOR = 70);

