CREATE TABLE [dbo].[ARCRHDR] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [CRMEMO_#]    DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [DATE]        DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ORDNUM]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [CHECKNUM]    DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [AMOUNT]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [REFUND_FLAG] VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [BCUSTID]     VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [TAX]         DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [OWED]        DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [ID]          DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [Total]       DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ARCRHDR_INDEX01] PRIMARY KEY CLUSTERED ([CRMEMO_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRHDR_INDEX00]
    ON [dbo].[ARCRHDR]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRHDR_INDEX02]
    ON [dbo].[ARCRHDR]([DATE] ASC, [CRMEMO_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRHDR_INDEX03]
    ON [dbo].[ARCRHDR]([ORDNUM] ASC, [CRMEMO_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRHDR_INDEX04]
    ON [dbo].[ARCRHDR]([CHECKNUM] ASC, [CRMEMO_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ARCRHDR_INDEX05]
    ON [dbo].[ARCRHDR]([BCUSTID] ASC, [CRMEMO_#] ASC) WITH (FILLFACTOR = 70);

