CREATE TABLE [dbo].[GLREPORT] (
    [Recnum]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]       VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [FORMAT_#]        VARCHAR (3)    DEFAULT (' ') NOT NULL,
    [REPORT_#]        VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [REPORT_LINE_#]   DECIMAL (6)    DEFAULT ((0)) NOT NULL,
    [FUNCTION_ID]     VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [LINE_DESC]       VARCHAR (40)   DEFAULT (' ') NOT NULL,
    [FROM_ACCT_DIV_#] VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [FROM_ACCT_ACC_#] VARCHAR (5)    DEFAULT (' ') NOT NULL,
    [TO_ACCT_DIV_#]   VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [TO_ACCT_ACC_#]   VARCHAR (5)    DEFAULT (' ') NOT NULL,
    [INDENTION]       DECIMAL (2)    DEFAULT ((0)) NOT NULL,
    [LINE_FEEDS]      DECIMAL (2)    DEFAULT ((0)) NOT NULL,
    [TOTAL_LEVEL]     DECIMAL (2)    DEFAULT ((0)) NOT NULL,
    [TOTAL_LEVEL_2]   DECIMAL (2)    DEFAULT ((0)) NOT NULL,
    [UNDERSCORE]      VARCHAR (1)    DEFAULT (' ') NOT NULL,
    [FX_PERCNT]       DECIMAL (8, 4) DEFAULT ((0)) NOT NULL,
    [ID]              DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLRPTMST_ID]     DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [GLFUNCT_ID]      DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLREPORT_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [FORMAT_#] ASC, [REPORT_#] ASC, [REPORT_LINE_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLREPORT_INDEX00]
    ON [dbo].[GLREPORT]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLREPORT_INDEX02]
    ON [dbo].[GLREPORT]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLREPORT_INDEX03]
    ON [dbo].[GLREPORT]([GLRPTMST_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLREPORT_INDEX04]
    ON [dbo].[GLREPORT]([GLFUNCT_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

