CREATE TABLE [dbo].[VacaSys] (
    [Recnum]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [CurrentYear]     DECIMAL (4)    DEFAULT ((0)) NOT NULL,
    [AccrualType1]    VARCHAR (2)    CONSTRAINT [DF_VacaSys_AccrualType1] DEFAULT (' ') NOT NULL,
    [AccrualAmtV1]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecV1] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxV1]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtS1]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecS1] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxS1]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualType2]    VARCHAR (2)    CONSTRAINT [DF_VacaSys_AccrualType2] DEFAULT (' ') NOT NULL,
    [AccrualAmtV2]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecV2] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxV2]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtS2]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecS2] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxS2]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualType3]    VARCHAR (2)    CONSTRAINT [DF_VacaSys_AccrualType3] DEFAULT (' ') NOT NULL,
    [AccrualAmtV3]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecV3] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxV3]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtS3]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecS3] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxS3]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualType4]    VARCHAR (2)    CONSTRAINT [DF_VacaSys_AccrualType4] DEFAULT (' ') NOT NULL,
    [AccrualAmtV4]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecV4] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxV4]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtS4]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecS4] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxS4]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualType5]    VARCHAR (2)    CONSTRAINT [DF_VacaSys_AccrualType5] DEFAULT (' ') NOT NULL,
    [AccrualAmtV5]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecV5] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxV5]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtS5]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [AccrualAmtDecS5] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [MaxS5]           DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [VacaSys_INDEX00] PRIMARY KEY CLUSTERED ([Recnum] ASC) WITH (FILLFACTOR = 70)
);

