CREATE TABLE [dbo].[EDI850AIMOrders] (
    [ID]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [EDI850HeaderID] BIGINT          CONSTRAINT [DF__EDI850AIM__EDI85__156A2EB6] DEFAULT ((0)) NOT NULL,
    [AIMOrdnum]      NUMERIC (10, 2) CONSTRAINT [DF__EDI850AIM__AIMOr__165E52EF] DEFAULT ((0)) NOT NULL,
    [RefBB]          VARCHAR (15)    NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [EDI850AIMOrders_INDEX03]
    ON [dbo].[EDI850AIMOrders]([AIMOrdnum] ASC, [EDI850HeaderID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [EDI850AIMOrders_INDEX02]
    ON [dbo].[EDI850AIMOrders]([EDI850HeaderID] ASC, [AIMOrdnum] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [EDI850AIMOrders_INDEX01]
    ON [dbo].[EDI850AIMOrders]([ID] ASC);

