CREATE TABLE [dbo].[WOHeader] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [WO_#]          DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [SPRNUM]        VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [STATUS]        VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [TARGET]        DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [OPEN_DATE]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [CLOSE_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [QTY_PROJ]      DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [AVAIL]         DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [ORDNUM]        DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [STD_LABOR]     DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [STD_OVERHEAD]  DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [STD_INDIRECT]  DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [STD_SUBCONTR]  DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [STD_MATERIALS] DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [UNIT_COST]     DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [NEXT_LINE]     DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [INV_FLAG]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PRINT_#]       VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [ACT_LABOR]     DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [ACT_OVERHEAD]  DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [ACT_INDIRECT]  DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [ACT_SUBCONTR]  DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [ACT_MATERIALS] DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [ACTIVE_PICK]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [MAT_CST_FLAG]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [RELEASE_#]     DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [SHOP_FLAG]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [STOCK_FLAG]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [RECALC_FLAG]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [CreatedBy]     VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [CreatedDate]   DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]     VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [ChangedDate]   DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [Version]       VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [CloseInfo]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    CONSTRAINT [WOHeader_INDEX01] PRIMARY KEY CLUSTERED ([WO_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOHeader_INDEX00]
    ON [dbo].[WOHeader]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOHeader_INDEX02]
    ON [dbo].[WOHeader]([SPRNUM] ASC, [WO_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOHeader_INDEX03]
    ON [dbo].[WOHeader]([STATUS] ASC, [WO_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOHeader_INDEX04]
    ON [dbo].[WOHeader]([ORDNUM] ASC, [SPRNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOHeader_INDEX05]
    ON [dbo].[WOHeader]([TARGET] ASC, [SPRNUM] ASC, [WO_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOHeader_INDEX06]
    ON [dbo].[WOHeader]([CLOSE_DATE] ASC, [WO_#] ASC) WITH (FILLFACTOR = 70);

