CREATE TABLE [dbo].[RCHSTDTL] (
    [Recnum]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [TICKET]         DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [LINE]           DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [REFERENCE_LINE] DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [DATE_RECV]      DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [SPRNUM]         VARCHAR (20) DEFAULT (' ') NOT NULL,
    [DESC]           VARCHAR (30) DEFAULT (' ') NOT NULL,
    [QTY]            DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [RAWFIN]         VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [CLOSE_FLAG]     VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [INSPECT_FLAG]   VARCHAR (1)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [RCHSTDTL_INDEX01] PRIMARY KEY CLUSTERED ([TICKET] ASC, [LINE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RCHSTDTL_INDEX00]
    ON [dbo].[RCHSTDTL]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RCHSTDTL_INDEX02]
    ON [dbo].[RCHSTDTL]([SPRNUM] ASC, [DATE_RECV] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RCHSTDTL_INDEX03]
    ON [dbo].[RCHSTDTL]([DATE_RECV] ASC, [SPRNUM] ASC, [Recnum] ASC);

