CREATE TABLE [dbo].[PRICDET] (
    [Recnum]    BIGINT       IDENTITY (1, 1) NOT NULL,
    [ID]        VARCHAR (20) DEFAULT (' ') NOT NULL,
    [LINE]      DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [FUNCTION]  VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [SPRNUM]    VARCHAR (20) DEFAULT (' ') NOT NULL,
    [MAIN_TEXT] VARCHAR (70) DEFAULT (' ') NOT NULL,
    [SUB_TEXT]  VARCHAR (6)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [PRICDET_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC, [LINE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PRICDET_INDEX00]
    ON [dbo].[PRICDET]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PRICDET_INDEX02]
    ON [dbo].[PRICDET]([SPRNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

