CREATE TABLE [dbo].[WOPICK] (
    [Recnum]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [WO_#]        DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [SPRNUM]      VARCHAR (20) DEFAULT (' ') NOT NULL,
    [NEEDED]      DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [TO_PICK]     DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [PULLED]      DECIMAL (8)  DEFAULT ((0)) NOT NULL,
    [INV_STATE]   VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [DATE]        DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [TIME]        DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [FLAG]        VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [CreatedBy]   VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [CreatedDate] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]   VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [ChangedDate] DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [Version]     VARCHAR (15) DEFAULT (' ') NOT NULL,
    CONSTRAINT [WOPICK_INDEX01] PRIMARY KEY CLUSTERED ([WO_#] ASC, [SPRNUM] ASC, [DATE] ASC, [TIME] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOPICK_INDEX00]
    ON [dbo].[WOPICK]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOPICK_INDEX02]
    ON [dbo].[WOPICK]([SPRNUM] ASC, [WO_#] ASC, [DATE] ASC, [TIME] ASC) WITH (FILLFACTOR = 70);

