CREATE TABLE [dbo].[DINVMON] (
    [Recnum]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [DISTRIBUTOR] VARCHAR (20) DEFAULT (' ') NOT NULL,
    [MONTH]       DECIMAL (2)  DEFAULT ((0)) NOT NULL,
    [YEAR]        DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [SPRNUM]      VARCHAR (20) DEFAULT (' ') NOT NULL,
    [GROUP]       VARCHAR (7)  DEFAULT (' ') NOT NULL,
    [AMOUNT]      DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [TOTAL]       DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    CONSTRAINT [DINVMON_INDEX01] PRIMARY KEY CLUSTERED ([DISTRIBUTOR] ASC, [MONTH] ASC, [YEAR] ASC, [SPRNUM] ASC, [GROUP] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_DINVMON_SPRNUM] FOREIGN KEY ([SPRNUM]) REFERENCES [dbo].[parts] ([SPRNUM])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [DINVMON_INDEX00]
    ON [dbo].[DINVMON]([Recnum] ASC) WITH (FILLFACTOR = 70);

