CREATE TABLE [dbo].[VacaHdr] (
    [Recnum]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [ID]            DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [COMPANY_NO]    VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [DIVISION_NO]   VARCHAR (2)    DEFAULT (' ') NOT NULL,
    [EMPLOYEE_ID]   VARCHAR (10)   DEFAULT (' ') NOT NULL,
    [Year]          DECIMAL (4)    DEFAULT ((0)) NOT NULL,
    [LastUpdated]   DATETIME       DEFAULT ('01/01/1753') NOT NULL,
    [TotalVacation] DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [TotalSick]     DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [UseOrLoseV]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    [UseOrLoseS]    DECIMAL (6, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [VacaHdr_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [VacaHdr_INDEX00]
    ON [dbo].[VacaHdr]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [VacaHdr_INDEX02]
    ON [dbo].[VacaHdr]([COMPANY_NO] ASC, [DIVISION_NO] ASC, [EMPLOYEE_ID] ASC, [Year] DESC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [VacaHdr_INDEX03]
    ON [dbo].[VacaHdr]([EMPLOYEE_ID] ASC, [Year] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [VacaHdr_INDEX04]
    ON [dbo].[VacaHdr]([Year] ASC, [EMPLOYEE_ID] ASC) WITH (FILLFACTOR = 70);

