CREATE TABLE [dbo].[RMACodes] (
    [ID]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [TYPE]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [CODE]        CHAR (10)     DEFAULT (' ') NOT NULL,
    [DESCRIPTION] VARCHAR (255) NULL,
    [STATUS]      CHAR (1)      DEFAULT ('A') NOT NULL,
    [CreatedBy]   CHAR (4)      NULL,
    [CreatedDate] DATETIME2 (0) NULL,
    CONSTRAINT [RMACodes_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RMACodes_INDEX03]
    ON [dbo].[RMACodes]([TYPE] ASC, [DESCRIPTION] ASC, [CODE] ASC) WITH (FILLFACTOR = 100);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RMACodes_INDEX02]
    ON [dbo].[RMACodes]([TYPE] ASC, [CODE] ASC) WITH (FILLFACTOR = 100);

