CREATE TABLE [dbo].[PRWKCOMP] (
    [Recnum]      BIGINT         IDENTITY (1, 1) NOT NULL,
    [TYPE]        VARCHAR (3)    DEFAULT (' ') NOT NULL,
    [PERCENTAGE]  DECIMAL (6, 4) DEFAULT ((0)) NOT NULL,
    [DESCRIPTION] VARCHAR (25)   DEFAULT (' ') NOT NULL,
    CONSTRAINT [PRWKCOMP_INDEX01] PRIMARY KEY CLUSTERED ([TYPE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PRWKCOMP_INDEX00]
    ON [dbo].[PRWKCOMP]([Recnum] ASC) WITH (FILLFACTOR = 70);

