CREATE TABLE [dbo].[GLTYPE] (
    [Recnum]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [ACCT_TYPE]   VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [DESCRIPTION] VARCHAR (20) DEFAULT (' ') NOT NULL,
    [NORMAL_BAL]  VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [ID]          DECIMAL (10) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLTYPE_INDEX01] PRIMARY KEY CLUSTERED ([ACCT_TYPE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLTYPE_INDEX00]
    ON [dbo].[GLTYPE]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLTYPE_INDEX02]
    ON [dbo].[GLTYPE]([ID] ASC) WITH (FILLFACTOR = 70);

