CREATE TABLE [dbo].[GLRptCOG] (
    [Recnum]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [USER]           VARCHAR (12)    NOT NULL,
    [SPRNUM]         VARCHAR (20)    NOT NULL,
    [ORDNUM]         DECIMAL (10, 2) NOT NULL,
    [M_QTY_SHIP]     DECIMAL (8)     NOT NULL,
    [TOT_INCOME]     DECIMAL (14, 4) NOT NULL,
    [ACT_TOT_CST]    DECIMAL (14, 4) NOT NULL,
    [ACT_GM_EA]      DECIMAL (14, 4) NOT NULL,
    [ACT_TOT_MARGIN] DECIMAL (14, 4) NOT NULL,
    [STD_TOT_COST]   DECIMAL (14, 4) NOT NULL,
    [STD_TOT_MARGIN] DECIMAL (14, 4) NOT NULL,
    [STD]            VARCHAR (1)     NOT NULL,
    [ACT_MATERIALS]  DECIMAL (14, 4) NOT NULL,
    [ACT_DIR_LABOR]  DECIMAL (14, 4) NOT NULL,
    [ACT_FAC_OVER]   DECIMAL (14, 4) NOT NULL,
    [ACT_SUBCON]     DECIMAL (14, 4) NOT NULL,
    [STD_MATERIAL]   DECIMAL (14, 4) NOT NULL,
    [STD_DIR_LABOR]  DECIMAL (14, 4) NOT NULL,
    [STD_FAC_OVER]   DECIMAL (14, 4) NOT NULL,
    [STD_SUBCON]     DECIMAL (14, 4) NOT NULL,
    [Acct]           VARCHAR (20)    NULL,
    [International]  VARCHAR (1)     NULL,
    [Rpt_Group]      VARCHAR (6)     NULL,
    CONSTRAINT [GLRptCOG_INDEX01] PRIMARY KEY CLUSTERED ([USER] ASC, [SPRNUM] ASC, [ORDNUM] ASC, [Recnum] ASC)
);






GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRptCOG_INDEX00]
    ON [dbo].[GLRptCOG]([Recnum] ASC);

