CREATE TABLE [dbo].[EMAILPRE] (
    [Recnum]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [ID]          DECIMAL (8)   DEFAULT ((0)) NOT NULL,
    [Type]        VARCHAR (20)  DEFAULT (' ') NOT NULL,
    [Description] VARCHAR (60)  DEFAULT (' ') NOT NULL,
    [ShowToSales] VARCHAR (1)   DEFAULT (' ') NOT NULL,
    [Subject]     VARCHAR (150) DEFAULT (' ') NOT NULL,
    [Body]        VARCHAR (MAX) NULL,
    [Attach1]     VARCHAR (60)  DEFAULT (' ') NOT NULL,
    [Attach2]     VARCHAR (60)  DEFAULT (' ') NOT NULL,
    [Attach3]     VARCHAR (60)  DEFAULT (' ') NOT NULL,
    [Attach4]     VARCHAR (60)  DEFAULT (' ') NOT NULL,
    [Attach5]     VARCHAR (60)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [EMAILPRE_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [EMAILPRE_INDEX00]
    ON [dbo].[EMAILPRE]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [EMAILPRE_INDEX02]
    ON [dbo].[EMAILPRE]([Description] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [EMAILPRE_INDEX03]
    ON [dbo].[EMAILPRE]([Type] ASC, [Description] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [EMAILPRE_INDEX04]
    ON [dbo].[EMAILPRE]([ShowToSales] ASC, [Type] ASC, [Description] ASC) WITH (FILLFACTOR = 70);

