CREATE TABLE [dbo].[GLMASTER] (
    [Recnum]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]       VARCHAR (2)     CONSTRAINT [DF__GLMASTER__COMPAN__3BE1AFFD] DEFAULT (' ') NOT NULL,
    [DIVISION_#]      VARCHAR (2)     CONSTRAINT [DF__GLMASTER__DIVISI__3CD5D436] DEFAULT (' ') NOT NULL,
    [DEPARTMENT_#]    VARCHAR (2)     CONSTRAINT [DF__GLMASTER__DEPART__3DC9F86F] DEFAULT (' ') NOT NULL,
    [ACCOUNT_#]       VARCHAR (3)     CONSTRAINT [DF__GLMASTER__ACCOUN__3EBE1CA8] DEFAULT (' ') NOT NULL,
    [ACCT_DESC]       VARCHAR (25)    CONSTRAINT [DF__GLMASTER__ACCT_D__3FB240E1] DEFAULT (' ') NOT NULL,
    [ACCT_TYPE]       VARCHAR (1)     CONSTRAINT [DF__GLMASTER__ACCT_T__40A6651A] DEFAULT (' ') NOT NULL,
    [NORMAL_BAL]      VARCHAR (1)     CONSTRAINT [DF__GLMASTER__NORMAL__419A8953] DEFAULT (' ') NOT NULL,
    [BEG_BAL_THIS_YR] DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BEG_BA__428EAD8C] DEFAULT ((0)) NOT NULL,
    [BEG_BAL_LAST_YR] DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BEG_BA__4382D1C5] DEFAULT ((0)) NOT NULL,
    [PERIOD_1]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__4476F5FE] DEFAULT ((0)) NOT NULL,
    [PERIOD_2]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__456B1A37] DEFAULT ((0)) NOT NULL,
    [PERIOD_3]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__465F3E70] DEFAULT ((0)) NOT NULL,
    [PERIOD_4]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__475362A9] DEFAULT ((0)) NOT NULL,
    [PERIOD_5]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__484786E2] DEFAULT ((0)) NOT NULL,
    [PERIOD_6]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__493BAB1B] DEFAULT ((0)) NOT NULL,
    [PERIOD_7]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__4A2FCF54] DEFAULT ((0)) NOT NULL,
    [PERIOD_8]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__4B23F38D] DEFAULT ((0)) NOT NULL,
    [PERIOD_9]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__4C1817C6] DEFAULT ((0)) NOT NULL,
    [PERIOD_10]       DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__4D0C3BFF] DEFAULT ((0)) NOT NULL,
    [PERIOD_11]       DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__4E006038] DEFAULT ((0)) NOT NULL,
    [PERIOD_12]       DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__4EF48471] DEFAULT ((0)) NOT NULL,
    [PERIOD_13]       DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PERIOD__4FE8A8AA] DEFAULT ((0)) NOT NULL,
    [BUDGET_1]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__50DCCCE3] DEFAULT ((0)) NOT NULL,
    [BUDGET_2]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__51D0F11C] DEFAULT ((0)) NOT NULL,
    [BUDGET_3]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__52C51555] DEFAULT ((0)) NOT NULL,
    [BUDGET_4]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__53B9398E] DEFAULT ((0)) NOT NULL,
    [BUDGET_5]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__54AD5DC7] DEFAULT ((0)) NOT NULL,
    [BUDGET_6]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__55A18200] DEFAULT ((0)) NOT NULL,
    [BUDGET_7]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__5695A639] DEFAULT ((0)) NOT NULL,
    [BUDGET_8]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__5789CA72] DEFAULT ((0)) NOT NULL,
    [BUDGET_9]        DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__587DEEAB] DEFAULT ((0)) NOT NULL,
    [BUDGET_10]       DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__597212E4] DEFAULT ((0)) NOT NULL,
    [BUDGET_11]       DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__5A66371D] DEFAULT ((0)) NOT NULL,
    [BUDGET_12]       DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__5B5A5B56] DEFAULT ((0)) NOT NULL,
    [BUDGET_13]       DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__BUDGET__5C4E7F8F] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_1]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___5D42A3C8] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_2]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___5E36C801] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_3]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___5F2AEC3A] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_4]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___601F1073] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_5]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___611334AC] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_6]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___620758E5] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_7]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___62FB7D1E] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_8]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___63EFA157] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_9]  DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___64E3C590] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_10] DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___65D7E9C9] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_11] DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___66CC0E02] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_12] DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___67C0323B] DEFAULT ((0)) NOT NULL,
    [PRIOR_PERIOD_13] DECIMAL (12, 2) CONSTRAINT [DF__GLMASTER__PRIOR___68B45674] DEFAULT ((0)) NOT NULL,
    [ID]              DECIMAL (10)    CONSTRAINT [DF__GLMASTER__ID__69A87AAD] DEFAULT ((0)) NOT NULL,
    [GLCOMPAN_ID]     DECIMAL (10)    CONSTRAINT [DF__GLMASTER__GLCOMP__6A9C9EE6] DEFAULT ((0)) NOT NULL,
    [GLTYPE_ID]       DECIMAL (10)    CONSTRAINT [DF__GLMASTER__GLTYPE__6B90C31F] DEFAULT ((0)) NOT NULL,
    [DIVACCT]         VARCHAR (5)     CONSTRAINT [DF__GLMASTER__DIVACC__6C84E758] DEFAULT (' ') NOT NULL,
    [ReportGroup]     VARCHAR (4)     CONSTRAINT [DF_GLMASTER_ReportGroup] DEFAULT (' ') NOT NULL,
    CONSTRAINT [GLMASTER_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [DEPARTMENT_#] ASC, [ACCOUNT_#] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_GLMASTER_GLTYPE_ID] FOREIGN KEY ([GLTYPE_ID]) REFERENCES [dbo].[GLTYPE] ([ID])
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX00]
    ON [dbo].[GLMASTER]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX02]
    ON [dbo].[GLMASTER]([COMPANY_#] ASC, [DIVISION_#] ASC, [ACCOUNT_#] ASC, [DEPARTMENT_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX03]
    ON [dbo].[GLMASTER]([COMPANY_#] ASC, [ACCOUNT_#] ASC, [DIVISION_#] ASC, [DEPARTMENT_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX04]
    ON [dbo].[GLMASTER]([COMPANY_#] ASC, [DEPARTMENT_#] ASC, [ACCOUNT_#] ASC, [DIVISION_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX05]
    ON [dbo].[GLMASTER]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX06]
    ON [dbo].[GLMASTER]([GLCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX07]
    ON [dbo].[GLMASTER]([GLTYPE_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX08]
    ON [dbo].[GLMASTER]([DIVACCT] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX09]
    ON [dbo].[GLMASTER]([ReportGroup] ASC, [DIVACCT] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLMASTER_INDEX10]
    ON [dbo].[GLMASTER]([ACCT_DESC] ASC, [Recnum] ASC);

