CREATE TABLE [dbo].[FEDBKIMP] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [GUNTYPE]     VARCHAR (1)     CONSTRAINT [DF__FEDBKIMP__GUNTYP__2DA89F3F] DEFAULT (' ') NOT NULL,
    [SERIAL]      VARCHAR (14)    CONSTRAINT [DF__FEDBKIMP__SERIAL__2E9CC378] DEFAULT (' ') NOT NULL,
    [RECEIVED]    DATETIME        CONSTRAINT [DF__FEDBKIMP__RECEIV__2F90E7B1] DEFAULT ('01/01/1753') NOT NULL,
    [MANUFACT]    VARCHAR (10)    CONSTRAINT [DF__FEDBKIMP__MANUFA__30850BEA] DEFAULT (' ') NOT NULL,
    [MODEL]       VARCHAR (10)    CONSTRAINT [DF__FEDBKIMP__MODEL__31793023] DEFAULT (' ') NOT NULL,
    [SEMIFULL]    VARCHAR (1)     CONSTRAINT [DF__FEDBKIMP__SEMIFU__326D545C] DEFAULT (' ') NOT NULL,
    [NAME]        VARCHAR (25)    CONSTRAINT [DF__FEDBKIMP__NAME__33617895] DEFAULT (' ') NOT NULL,
    [STREET]      VARCHAR (20)    CONSTRAINT [DF__FEDBKIMP__STREET__34559CCE] DEFAULT (' ') NOT NULL,
    [CITY]        VARCHAR (15)    CONSTRAINT [DF__FEDBKIMP__CITY__3549C107] DEFAULT (' ') NOT NULL,
    [STATE]       VARCHAR (2)     CONSTRAINT [DF__FEDBKIMP__STATE__363DE540] DEFAULT (' ') NOT NULL,
    [SPRNUM]      VARCHAR (20)    CONSTRAINT [DF__FEDBKIMP__SPRNUM__37320979] DEFAULT (' ') NOT NULL,
    [GUNMODEL]    VARCHAR (20)    CONSTRAINT [DF__FEDBKIMP__GUNMOD__38262DB2] DEFAULT (' ') NOT NULL,
    [SOLD]        DATETIME        CONSTRAINT [DF__FEDBKIMP__SOLD__391A51EB] DEFAULT ('01/01/1753') NOT NULL,
    [SONAME]      VARCHAR (25)    CONSTRAINT [DF__FEDBKIMP__SONAME__3A0E7624] DEFAULT (' ') NOT NULL,
    [SOSTREET]    VARCHAR (35)    CONSTRAINT [DF__FEDBKIMP__SOSTRE__3B029A5D] DEFAULT (' ') NOT NULL,
    [SOCITY]      VARCHAR (15)    CONSTRAINT [DF__FEDBKIMP__SOCITY__3BF6BE96] DEFAULT (' ') NOT NULL,
    [SOSTATE]     VARCHAR (2)     CONSTRAINT [DF__FEDBKIMP__SOSTAT__3CEAE2CF] DEFAULT (' ') NOT NULL,
    [SOLDFFL]     VARCHAR (10)    CONSTRAINT [DF__FEDBKIMP__SOLDFF__3DDF0708] DEFAULT (' ') NOT NULL,
    [ORDNUM]      DECIMAL (10, 2) CONSTRAINT [DF__FEDBKIMP__ORDNUM__3ED32B41] DEFAULT ((0)) NOT NULL,
    [TAG]         VARCHAR (6)     CONSTRAINT [DF__FEDBKIMP__TAG__3FC74F7A] DEFAULT (' ') NOT NULL,
    [SAFETY]      VARCHAR (1)     CONSTRAINT [DF__FEDBKIMP__SAFETY__40BB73B3] DEFAULT (' ') NOT NULL,
    [GUNSMITH]    VARCHAR (10)    CONSTRAINT [DF__FEDBKIMP__GUNSMI__41AF97EC] DEFAULT (' ') NOT NULL,
    [TAGNUM]      DECIMAL (6)     CONSTRAINT [DF__FEDBKIMP__TAGNUM__42A3BC25] DEFAULT ((0)) NOT NULL,
    [FEDCODE]     VARCHAR (1)     CONSTRAINT [DF__FEDBKIMP__FEDCOD__4397E05E] DEFAULT (' ') NOT NULL,
    [CALIBER]     VARCHAR (10)    CONSTRAINT [DF__FEDBKIMP__CALIBE__448C0497] DEFAULT (' ') NOT NULL,
    [WO_NUMBER]   DECIMAL (6)     CONSTRAINT [DF__FEDBKIMP__WO_NUM__458028D0] DEFAULT ((0)) NOT NULL,
    [COMMENT]     VARCHAR (20)    CONSTRAINT [DF__FEDBKIMP__COMMEN__46744D09] DEFAULT (' ') NOT NULL,
    [RCTICKET]    DECIMAL (6)     CONSTRAINT [DF__FEDBKIMP__RCTICK__47687142] DEFAULT ((0)) NOT NULL,
    [BAN_STATUS]  VARCHAR (1)     CONSTRAINT [DF__FEDBKIMP__BAN_ST__485C957B] DEFAULT (' ') NOT NULL,
    [LOCATION]    VARCHAR (20)    CONSTRAINT [DF__FEDBKIMP__LOCATI__4950B9B4] DEFAULT (' ') NOT NULL,
    [CHANGE_FLAG] VARCHAR (1)     CONSTRAINT [DF__FEDBKIMP__CHANGE__4A44DDED] DEFAULT (' ') NOT NULL,
    [INITIALS]    VARCHAR (10)    CONSTRAINT [DF__FEDBKIMP__INITIA__4B390226] DEFAULT (' ') NOT NULL,
    [MANUFFL]     VARCHAR (20)    CONSTRAINT [DF__FEDBKIMP__MANUFF__4C2D265F] DEFAULT (' ') NOT NULL,
    [CreatedBy]   VARCHAR (4)     CONSTRAINT [DF__FEDBKIMP__Create__4D214A98] DEFAULT (' ') NOT NULL,
    [CreatedDate] DATETIME        CONSTRAINT [DF__FEDBKIMP__Create__4E156ED1] DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]   VARCHAR (4)     CONSTRAINT [DF__FEDBKIMP__Change__4F09930A] DEFAULT (' ') NOT NULL,
    [ChangedDate] DATETIME        CONSTRAINT [DF__FEDBKIMP__Change__4FFDB743] DEFAULT ('01/01/1753') NOT NULL,
    [Version]     VARCHAR (15)    CONSTRAINT [DF__FEDBKIMP__Versio__50F1DB7C] DEFAULT (' ') NOT NULL,
    CONSTRAINT [FEDBKIMP_INDEX01] PRIMARY KEY CLUSTERED ([GUNTYPE] ASC, [SERIAL] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_FEDBKIMP_FEDCODE] FOREIGN KEY ([FEDCODE]) REFERENCES [dbo].[FEDCODE] ([GROUP_CODE]),
    CONSTRAINT [FK_FEDBKIMP_SPRNUM] FOREIGN KEY ([SPRNUM]) REFERENCES [dbo].[parts] ([SPRNUM])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX00]
    ON [dbo].[FEDBKIMP]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX02]
    ON [dbo].[FEDBKIMP]([ORDNUM] ASC, [GUNTYPE] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX03]
    ON [dbo].[FEDBKIMP]([TAGNUM] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX04]
    ON [dbo].[FEDBKIMP]([RCTICKET] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX05]
    ON [dbo].[FEDBKIMP]([SONAME] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX06]
    ON [dbo].[FEDBKIMP]([SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX07]
    ON [dbo].[FEDBKIMP]([GUNTYPE] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX08]
    ON [dbo].[FEDBKIMP]([SERIAL] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBKIMP_INDEX09]
    ON [dbo].[FEDBKIMP]([NAME] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

