CREATE TABLE [dbo].[PARTNOUN] (
    [RECNUM]    INT          IDENTITY (1700, 1) NOT NULL,
    [NOUN]      VARCHAR (20) NOT NULL,
    [STR_COUNT] INT          NULL,
    [STATUS]    CHAR (1)     NOT NULL,
    CONSTRAINT [PK__PARTNOUN__E2AC6D7E13BD4B1B] PRIMARY KEY CLUSTERED ([NOUN] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PARTNOUN_INDEX02]
    ON [dbo].[PARTNOUN]([STATUS] ASC, [NOUN] ASC) WITH (FILLFACTOR = 100);

