CREATE TABLE [dbo].[APPerm] (
    [Recnum]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]        VARCHAR (2)     CONSTRAINT [DF__APPerm__COMPANY___2B2B59F0] DEFAULT (' ') NOT NULL,
    [DIVISION_#]       VARCHAR (2)     CONSTRAINT [DF__APPerm__DIVISION__2C1F7E29] DEFAULT (' ') NOT NULL,
    [VENDOR_#]         VARCHAR (8)     CONSTRAINT [DF__APPerm__VENDOR_#__2D13A262] DEFAULT (' ') NOT NULL,
    [INVOICE_#]        VARCHAR (15)    CONSTRAINT [DF__APPerm__INVOICE___2E07C69B] DEFAULT (' ') NOT NULL,
    [VOUCH_FLAG]       VARCHAR (1)     CONSTRAINT [DF__APPerm__VOUCH_FL__2EFBEAD4] DEFAULT (' ') NOT NULL,
    [VOUCHER_DATE]     DATETIME        CONSTRAINT [DF__APPerm__VOUCHER___2FF00F0D] DEFAULT ('01/01/1753') NOT NULL,
    [DUE_DATE]         DATETIME        CONSTRAINT [DF__APPerm__DUE_DATE__30E43346] DEFAULT ('01/01/1753') NOT NULL,
    [INVOICE_DATE]     DATETIME        CONSTRAINT [DF__APPerm__INVOICE___31D8577F] DEFAULT ('01/01/1753') NOT NULL,
    [AMOUNT_DUE]       DECIMAL (10, 2) CONSTRAINT [DF__APPerm__AMOUNT_D__32CC7BB8] DEFAULT ((0)) NOT NULL,
    [FREIGHT]          DECIMAL (8, 2)  CONSTRAINT [DF__APPerm__FREIGHT__33C09FF1] DEFAULT ((0)) NOT NULL,
    [TAX]              DECIMAL (6, 2)  CONSTRAINT [DF__APPerm__TAX__34B4C42A] DEFAULT ((0)) NOT NULL,
    [DISCOUNT_AMOUNT]  DECIMAL (10, 2) CONSTRAINT [DF__APPerm__DISCOUNT__35A8E863] DEFAULT ((0)) NOT NULL,
    [DISC_DATE]        DATETIME        CONSTRAINT [DF__APPerm__DISC_DAT__369D0C9C] DEFAULT ('01/01/1753') NOT NULL,
    [DISC_PERCENT]     DECIMAL (8, 4)  CONSTRAINT [DF__APPerm__DISC_PER__379130D5] DEFAULT ((0)) NOT NULL,
    [DISCOUNT_FLAG]    VARCHAR (1)     CONSTRAINT [DF__APPerm__DISCOUNT__3885550E] DEFAULT (' ') NOT NULL,
    [REFERENCE]        VARCHAR (15)    CONSTRAINT [DF__APPerm__REFERENC__39797947] DEFAULT (' ') NOT NULL,
    [DISCOUNT_TAKEN]   VARCHAR (1)     CONSTRAINT [DF__APPerm__DISCOUNT__3A6D9D80] DEFAULT (' ') NOT NULL,
    [PAID_FLAG]        VARCHAR (1)     CONSTRAINT [DF__APPerm__PAID_FLA__3B61C1B9] DEFAULT (' ') NOT NULL,
    [PART_PAYMENTS]    DECIMAL (2)     CONSTRAINT [DF__APPerm__PART_PAY__3C55E5F2] DEFAULT ((0)) NOT NULL,
    [MANUAL_CHECKS]    DECIMAL (2)     CONSTRAINT [DF__APPerm__MANUAL_C__3D4A0A2B] DEFAULT ((0)) NOT NULL,
    [PRINT_FLAG]       VARCHAR (1)     CONSTRAINT [DF__APPerm__PRINT_FL__3E3E2E64] DEFAULT (' ') NOT NULL,
    [PAY_FLAG]         VARCHAR (1)     CONSTRAINT [DF__APPerm__PAY_FLAG__3F32529D] DEFAULT (' ') NOT NULL,
    [ORIG_AMOUNT]      DECIMAL (10, 2) CONSTRAINT [DF__APPerm__ORIG_AMO__402676D6] DEFAULT ((0)) NOT NULL,
    [EOM_FLAG]         VARCHAR (1)     CONSTRAINT [DF__APPerm__EOM_FLAG__411A9B0F] DEFAULT (' ') NOT NULL,
    [PAID_DATE]        DATETIME        CONSTRAINT [DF__APPerm__PAID_DAT__420EBF48] DEFAULT ('01/01/1753') NOT NULL,
    [CHECKNUM]         DECIMAL (6)     CONSTRAINT [DF__APPerm__CHECKNUM__4302E381] DEFAULT ((0)) NOT NULL,
    [PARTIAL_COUNTER]  DECIMAL (2)     CONSTRAINT [DF__APPerm__PARTIAL___43F707BA] DEFAULT ((0)) NOT NULL,
    [CASH_FLAG]        VARCHAR (1)     CONSTRAINT [DF__APPerm__CASH_FLA__44EB2BF3] DEFAULT (' ') NOT NULL,
    [MANCHECKS]        DECIMAL (6)     CONSTRAINT [DF__APPerm__MANCHECK__45DF502C] DEFAULT ((0)) NOT NULL,
    [MANUAL_FLAG]      VARCHAR (1)     CONSTRAINT [DF__APPerm__MANUAL_F__46D37465] DEFAULT (' ') NOT NULL,
    [VENDOR_NAME]      VARCHAR (30)    CONSTRAINT [DF__APPerm__VENDOR_N__47C7989E] DEFAULT (' ') NOT NULL,
    [ID]               DECIMAL (10)    CONSTRAINT [DF__APPerm__ID__48BBBCD7] DEFAULT ((0)) NOT NULL,
    [APVENDOR_ID]      DECIMAL (10)    CONSTRAINT [DF__APPerm__APVENDOR__49AFE110] DEFAULT ((0)) NOT NULL,
    [APCOMPAN_ID]      DECIMAL (10)    CONSTRAINT [DF__APPerm__APCOMPAN__4AA40549] DEFAULT ((0)) NOT NULL,
    [APMANCHK_ID]      DECIMAL (10)    CONSTRAINT [DF__APPerm__APMANCHK__4B982982] DEFAULT ((0)) NOT NULL,
    [VOID_FLAG]        VARCHAR (1)     CONSTRAINT [DF__APPerm__VOID_FLA__4C8C4DBB] DEFAULT (' ') NOT NULL,
    [SIGNATURE_1]      VARCHAR (10)    NULL,
    [SIGNATURE_2]      VARCHAR (10)    NULL,
    [CHECK_CREATED_BY] VARCHAR (10)    NULL,
    CONSTRAINT [APPerm_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [INVOICE_#] ASC, [VOUCH_FLAG] ASC) WITH (FILLFACTOR = 70)
);






GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX00]
    ON [dbo].[APPerm]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX02]
    ON [dbo].[APPerm]([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [MANCHECKS] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX03]
    ON [dbo].[APPerm]([COMPANY_#] ASC, [DIVISION_#] ASC, [VENDOR_#] ASC, [MANCHECKS] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX04]
    ON [dbo].[APPerm]([CHECKNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX05]
    ON [dbo].[APPerm]([PAID_DATE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX06]
    ON [dbo].[APPerm]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX07]
    ON [dbo].[APPerm]([APVENDOR_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX08]
    ON [dbo].[APPerm]([APCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX09]
    ON [dbo].[APPerm]([APMANCHK_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX10]
    ON [dbo].[APPerm]([COMPANY_#] ASC, [DIVISION_#] ASC, [PAID_FLAG] ASC, [VOID_FLAG] ASC, [VENDOR_#] ASC, [INVOICE_#] ASC, [ID] ASC);

GO

CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX11]
    ON [dbo].[APPerm]([VOUCHER_DATE] ASC, [VENDOR_#] ASC, [ID] ASC) WITH (FILLFACTOR = 100);
GO

CREATE UNIQUE NONCLUSTERED INDEX [APPerm_INDEX12]
    ON [dbo].[APPerm]([INVOICE_DATE] ASC, [VENDOR_#] ASC, [ID] ASC) WITH (FILLFACTOR = 100);
