CREATE TABLE [dbo].[GLRPTMST] (
    [Recnum]        BIGINT       IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]     VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [FORMAT_#]      VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [REPORT_#]      VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DESCRIPTION_1] VARCHAR (40) DEFAULT (' ') NOT NULL,
    [DESCRIPTION_2] VARCHAR (40) DEFAULT (' ') NOT NULL,
    [ID]            DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [GLRPTFMT_ID]   DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [GLRBATCH_ID]   DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [GLJOURN_ID]    DECIMAL (10) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLRPTMST_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [FORMAT_#] ASC, [REPORT_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRPTMST_INDEX00]
    ON [dbo].[GLRPTMST]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRPTMST_INDEX02]
    ON [dbo].[GLRPTMST]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRPTMST_INDEX03]
    ON [dbo].[GLRPTMST]([GLRPTFMT_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRPTMST_INDEX04]
    ON [dbo].[GLRPTMST]([GLRBATCH_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRPTMST_INDEX05]
    ON [dbo].[GLRPTMST]([GLJOURN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

