CREATE TABLE [dbo].[GLXREF] (
    [Recnum]       BIGINT       IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]    VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DIVISION_#]   VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [DEPARTMENT_#] VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [ACCOUNT_#]    VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [DESCRIPTION]  VARCHAR (30) DEFAULT (' ') NOT NULL,
    [JCFLAG]       VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [INFLAG]       VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [ID]           DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [DIVACCT]      VARCHAR (7)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [GLXREF_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [DEPARTMENT_#] ASC, [ACCOUNT_#] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLXREF_INDEX00]
    ON [dbo].[GLXREF]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLXREF_INDEX02]
    ON [dbo].[GLXREF]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLXREF_INDEX03]
    ON [dbo].[GLXREF]([DIVACCT] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLXREF_INDEX04]
    ON [dbo].[GLXREF]([DEPARTMENT_#] ASC, [ACCOUNT_#] ASC, [Recnum] ASC);

