CREATE TABLE [dbo].[WOTEMPLT] (
    [Recnum]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [SPRNUM]          VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [LINE]            DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [LOCATION]        VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [MACHINE]         VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [OPERATION]       VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [OPER_TYPE]       VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [NUMNOTES]        DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [QUAN]            DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [MACH_TIME]       DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [STD_TIME]        DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [STD_MATERIAL]    DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [STD_SUBCONTRACT] DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [UNIT_MEAS]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ACTIVE_FLAG]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PRINT_NUMBER]    VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [PIECES_PER_HOUR] DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [CreatedBy]       VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [CreatedDate]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]       VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [ChangedDate]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [Version]         VARCHAR (15)    DEFAULT (' ') NOT NULL,
    CONSTRAINT [WOTEMPLT_INDEX01] PRIMARY KEY CLUSTERED ([SPRNUM] ASC, [LINE] ASC),
    CONSTRAINT [FK_WOTEMPLT_LOCATION] FOREIGN KEY ([LOCATION]) REFERENCES [dbo].[WOLOCATN] ([NUM]),
    CONSTRAINT [FK_WOTEMPLT_MACHINE] FOREIGN KEY ([MACHINE]) REFERENCES [dbo].[WOMACHIN] ([NUM])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTEMPLT_INDEX00]
    ON [dbo].[WOTEMPLT]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTEMPLT_INDEX02]
    ON [dbo].[WOTEMPLT]([SPRNUM] ASC, [LOCATION] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTEMPLT_INDEX03]
    ON [dbo].[WOTEMPLT]([SPRNUM] ASC, [MACHINE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTEMPLT_INDEX10]
    ON [dbo].[WOTEMPLT]([SPRNUM] ASC, [LOCATION] ASC, [MACHINE] ASC, [OPERATION] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTEMPLT_INDEX04]
    ON [dbo].[WOTEMPLT]([SPRNUM] ASC, [LINE] ASC);

