CREATE TABLE [dbo].[APRECON] (
    [Recnum]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]      VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [VENDOR_#]       VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [CHECK_DATE]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [CHECK_NO]       DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [AMOUNT]         DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [MANUAL_FLAG]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [RECONCILE_FLAG] VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [VOID_FLAG]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [ID]             DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APVENDOR_ID]    DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [APCOMPAN_ID]    DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [APRECON_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [CHECK_NO] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APRECON_INDEX00]
    ON [dbo].[APRECON]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APRECON_INDEX02]
    ON [dbo].[APRECON]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APRECON_INDEX03]
    ON [dbo].[APRECON]([APVENDOR_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [APRECON_INDEX04]
    ON [dbo].[APRECON]([APCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

