CREATE TABLE [dbo].[GLRPTFMT] (
    [Recnum]       BIGINT       IDENTITY (1, 1) NOT NULL,
    [FORMAT_ID]    VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [FORMAT_DESC]  VARCHAR (40) DEFAULT (' ') NOT NULL,
    [PROGRAM_NAME] VARCHAR (10) DEFAULT (' ') NOT NULL,
    [ID]           DECIMAL (10) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [GLRPTFMT_INDEX01] PRIMARY KEY CLUSTERED ([FORMAT_ID] ASC, [FORMAT_DESC] ASC, [PROGRAM_NAME] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRPTFMT_INDEX00]
    ON [dbo].[GLRPTFMT]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRPTFMT_INDEX02]
    ON [dbo].[GLRPTFMT]([ID] ASC) WITH (FILLFACTOR = 70);

