CREATE TABLE [dbo].[PLBarrel] (
    [Recnum]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [ID]            DECIMAL (10)   DEFAULT ((0)) NOT NULL,
    [Barrel_Length] DECIMAL (4, 2) DEFAULT ((0)) NOT NULL,
    [Description]   VARCHAR (50)   DEFAULT (' ') NOT NULL,
    CONSTRAINT [PLBarrel_INDEX01] PRIMARY KEY CLUSTERED ([Barrel_Length] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PLBarrel_INDEX00]
    ON [dbo].[PLBarrel]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PLBarrel_INDEX02]
    ON [dbo].[PLBarrel]([ID] ASC) WITH (FILLFACTOR = 70);

