CREATE TABLE [dbo].[WOTMPNOT] (
    [Recnum]    BIGINT       IDENTITY (1, 1) NOT NULL,
    [SPRNUM]    VARCHAR (20) DEFAULT (' ') NOT NULL,
    [TMP_LINE]  DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [LINE]      DECIMAL (4)  DEFAULT ((0)) NOT NULL,
    [NOTE_CODE] VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [DESC]      VARCHAR (30) DEFAULT (' ') NOT NULL,
    CONSTRAINT [WOTMPNOT_INDEX01] PRIMARY KEY CLUSTERED ([SPRNUM] ASC, [TMP_LINE] ASC, [LINE] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTMPNOT_INDEX00]
    ON [dbo].[WOTMPNOT]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTMPNOT_INDEX02]
    ON [dbo].[WOTMPNOT]([SPRNUM] ASC, [TMP_LINE] ASC, [LINE] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOTMPNOT_INDEX03]
    ON [dbo].[WOTMPNOT]([SPRNUM] ASC, [TMP_LINE] ASC, [Recnum] ASC);

