CREATE TABLE [dbo].[GLRET] (
    [Recnum]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]    VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]   VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [RE_ACCOUNT_#] VARCHAR (5)     DEFAULT (' ') NOT NULL,
    [RE_DOLLARS]   DECIMAL (14, 2) DEFAULT ((0)) NOT NULL,
    [ID]           DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLMASTER_ID]  DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [DIVACCT]      VARCHAR (5)     DEFAULT (' ') NOT NULL,
    CONSTRAINT [GLRET_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_GLRET_GLMASTER_ID] FOREIGN KEY ([GLMASTER_ID]) REFERENCES [dbo].[GLMASTER] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRET_INDEX00]
    ON [dbo].[GLRET]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRET_INDEX02]
    ON [dbo].[GLRET]([COMPANY_#] ASC, [DIVISION_#] ASC, [RE_ACCOUNT_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRET_INDEX03]
    ON [dbo].[GLRET]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLRET_INDEX04]
    ON [dbo].[GLRET]([GLMASTER_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

