CREATE TABLE [dbo].[WOMNOTE] (
    [Recnum]    BIGINT       IDENTITY (1, 1) NOT NULL,
    [ID]        VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [TEXT]      VARCHAR (30) DEFAULT (' ') NOT NULL,
    [ENTFLAG]   VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [PRINTFLAG] VARCHAR (1)  DEFAULT (' ') NOT NULL,
    CONSTRAINT [WOMNOTE_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WOMNOTE_INDEX00]
    ON [dbo].[WOMNOTE]([Recnum] ASC) WITH (FILLFACTOR = 70);

