CREATE TABLE [dbo].[GLBATCH] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]   VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]  VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [BATCH_#]     DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [BATCH_TYPE]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [DEBITS]      DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [CREDITS]     DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [BALANCE]     DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [POSTED_FLAG] VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [YEAR_#]      DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [PERIOD_#]    DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [LINE_#]      DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [TRN_LN#]     DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [ID]          DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLCOMPAN_ID] DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [POST#]       DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [POST_DATE]   DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    CONSTRAINT [GLBATCH_INDEX01] PRIMARY KEY CLUSTERED ([COMPANY_#] ASC, [DIVISION_#] ASC, [YEAR_#] ASC, [BATCH_#] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_GLBATCH_GLCOMPAN_ID] FOREIGN KEY ([GLCOMPAN_ID]) REFERENCES [dbo].[GLCOMPAN] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLBATCH_INDEX00]
    ON [dbo].[GLBATCH]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLBATCH_INDEX02]
    ON [dbo].[GLBATCH]([COMPANY_#] ASC, [DIVISION_#] ASC, [YEAR_#] ASC, [BATCH_TYPE] ASC, [BATCH_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLBATCH_INDEX03]
    ON [dbo].[GLBATCH]([COMPANY_#] ASC, [YEAR_#] ASC, [BATCH_#] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLBATCH_INDEX04]
    ON [dbo].[GLBATCH]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLBATCH_INDEX05]
    ON [dbo].[GLBATCH]([GLCOMPAN_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

