CREATE TABLE [dbo].[STRATTR] (
    [RECNUM]     INT           IDENTITY (1, 1) NOT NULL,
    [TID]        INT           NOT NULL,
    [PARTNUMBER] VARCHAR (40)  NOT NULL,
    [NOUN]       VARCHAR (20)  NOT NULL,
    [MODIFIER]   VARCHAR (30)  NOT NULL,
    [ATTRIBUTE]  VARCHAR (30)  NOT NULL,
    [POS]        SMALLINT      NOT NULL,
    [ADATA]      VARCHAR (196) NULL,
    CONSTRAINT [STRATTR000] PRIMARY KEY CLUSTERED ([RECNUM] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [STRATTR_INDEX03]
    ON [dbo].[STRATTR]([PARTNUMBER] ASC, [POS] ASC) WITH (FILLFACTOR = 100);


GO
CREATE UNIQUE NONCLUSTERED INDEX [STRATTR_INDEX02]
    ON [dbo].[STRATTR]([NOUN] ASC, [MODIFIER] ASC, [ATTRIBUTE] ASC, [PARTNUMBER] ASC) WITH (FILLFACTOR = 100);


GO
CREATE UNIQUE NONCLUSTERED INDEX [STRATTR_INDEX01]
    ON [dbo].[STRATTR]([TID] ASC, [PARTNUMBER] ASC, [POS] ASC) WITH (FILLFACTOR = 100);

