CREATE TABLE [dbo].[GLWORK] (
    [Recnum]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [COMPANY_#]      VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DIVISION_#]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [DEPARTMENT_#]   VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [ACCOUNT_#]      VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [YEAR_#]         DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [BATCH_#]        DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [LINE_#]         DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [BATCH_TYPE]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SOURCE]         VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [TRANS_DATE]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DEBIT_AMOUNT]   DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [CREDIT_AMOUNT]  DECIMAL (12, 2) DEFAULT ((0)) NOT NULL,
    [REFERENCE_DESC] VARCHAR (45)    DEFAULT (' ') NOT NULL,
    [POSTED_FLAG]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [PERIOD_#]       DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [ID]             DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLMASTER_ID]    DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [DIVACCT]        VARCHAR (5)     DEFAULT (' ') NOT NULL,
    CONSTRAINT [GLWORK_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_GLWORK_GLMASTER_ID] FOREIGN KEY ([GLMASTER_ID]) REFERENCES [dbo].[GLMASTER] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLWORK_INDEX00]
    ON [dbo].[GLWORK]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLWORK_INDEX02]
    ON [dbo].[GLWORK]([GLMASTER_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

