CREATE TABLE [dbo].[People] (
    [Recnum]        BIGINT        IDENTITY (1, 1) NOT NULL,
    [ID]            DECIMAL (10)  DEFAULT ((0)) NOT NULL,
    [CUSTID]        VARCHAR (10)  DEFAULT (' ') NOT NULL,
    [PREFIX]        VARCHAR (4)   DEFAULT (' ') NOT NULL,
    [FIRST_NAME]    VARCHAR (20)  DEFAULT (' ') NOT NULL,
    [INITIAL]       VARCHAR (1)   DEFAULT (' ') NOT NULL,
    [LAST_NAME]     VARCHAR (30)  DEFAULT (' ') NOT NULL,
    [SUFFIX]        VARCHAR (4)   DEFAULT (' ') NOT NULL,
    [EMAIL]         VARCHAR (100) DEFAULT (' ') NOT NULL,
    [TITLE]         VARCHAR (20)  DEFAULT (' ') NOT NULL,
    [EXT]           VARCHAR (4)   DEFAULT (' ') NOT NULL,
    [HOME_PHONE]    VARCHAR (14)  DEFAULT (' ') NOT NULL,
    [D_O_B]         DATETIME      DEFAULT ('01/01/1753') NOT NULL,
    [COMMENTS]      VARCHAR (MAX) NULL,
    [CELL_PHONE]    VARCHAR (14)  DEFAULT (' ') NOT NULL,
    [GetInvoice]    VARCHAR (1)   DEFAULT (' ') NOT NULL,
    [GetShipNotice] VARCHAR (1)   DEFAULT ('N') NOT NULL,
    CONSTRAINT [People_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC)
);






GO
CREATE UNIQUE NONCLUSTERED INDEX [People_INDEX00]
    ON [dbo].[People]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [People_INDEX02]
    ON [dbo].[People]([CUSTID] ASC, [LAST_NAME] ASC, [FIRST_NAME] ASC, [ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [People_INDEX03]
    ON [dbo].[People]([CUSTID] ASC, [FIRST_NAME] ASC, [LAST_NAME] ASC, [ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [People_INDEX04]
    ON [dbo].[People]([CUSTID] ASC, [LAST_NAME] ASC, [FIRST_NAME] ASC, [SUFFIX] ASC, [ID] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [People_INDEX05]
    ON [dbo].[People]([CUSTID] ASC, [EMAIL] ASC, [ID] ASC);

