CREATE TABLE [dbo].[SHIPCHG] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [ID]          DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [SHIP_CHARGE] DECIMAL (10, 2) NOT NULL,
    [Type]        VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [AmountFrom]  NUMERIC (10, 2) NULL,
    [AmountTo]    NUMERIC (10, 2) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [SHIPCHG_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SHIPCHG_INDEX00]
    ON [dbo].[SHIPCHG]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SHIPCHG_INDEX02]
    ON [dbo].[SHIPCHG]([Type] ASC, [AmountTo] ASC, [ID] ASC);

