CREATE TABLE [dbo].[POSHIPTO] (
    [Recnum]    BIGINT       IDENTITY (1, 1) NOT NULL,
    [VENDOR_ID] VARCHAR (8)  DEFAULT (' ') NOT NULL,
    [PO_#]      DECIMAL (6)  DEFAULT ((0)) NOT NULL,
    [UNUSED]    VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [NAME]      VARCHAR (25) DEFAULT (' ') NOT NULL,
    [ADDRESS1]  VARCHAR (25) DEFAULT (' ') NOT NULL,
    [ADDRESS2]  VARCHAR (25) DEFAULT (' ') NOT NULL,
    [CITY]      VARCHAR (18) DEFAULT (' ') NOT NULL,
    [STATE]     VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [ZIP]       VARCHAR (10) DEFAULT (' ') NOT NULL,
    [CONTACT]   VARCHAR (18) DEFAULT (' ') NOT NULL,
    [PHONE]     VARCHAR (12) DEFAULT (' ') NOT NULL,
    [CUST_PO_#] VARCHAR (15) DEFAULT (' ') NOT NULL,
    CONSTRAINT [POSHIPTO_INDEX01] PRIMARY KEY CLUSTERED ([VENDOR_ID] ASC, [PO_#] ASC, [UNUSED] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [POSHIPTO_INDEX00]
    ON [dbo].[POSHIPTO]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [POSHIPTO_INDEX02]
    ON [dbo].[POSHIPTO]([PO_#] ASC) WITH (FILLFACTOR = 70);

