CREATE TABLE [dbo].[WARRANTY] (
    [Recnum]           INT          IDENTITY (1, 1) NOT NULL,
    [SERIALNUM]        VARCHAR (14) DEFAULT (' ') NOT NULL,
    [GUNMODEL]         VARCHAR (20) DEFAULT (' ') NOT NULL,
    [SPRNUM]           VARCHAR (20) DEFAULT (' ') NOT NULL,
    [CALIBER]          VARCHAR (10) DEFAULT (' ') NOT NULL,
    [BARRELLENGTH]     VARCHAR (10) DEFAULT (' ') NOT NULL,
    [FIRST_NAME]       VARCHAR (30) DEFAULT (' ') NOT NULL,
    [MID_INITIAL]      VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [LAST_NAME]        VARCHAR (50) DEFAULT (' ') NOT NULL,
    [STREET_ADD1]      VARCHAR (30) DEFAULT (' ') NOT NULL,
    [STREET_ADD2]      VARCHAR (30) DEFAULT (' ') NOT NULL,
    [APT_NO]           VARCHAR (10) DEFAULT (' ') NOT NULL,
    [CITY]             VARCHAR (30) DEFAULT (' ') NOT NULL,
    [STATE]            VARCHAR (2)  DEFAULT (' ') NOT NULL,
    [STATE_INT]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [ZIP]              VARCHAR (10) DEFAULT (' ') NOT NULL,
    [COUNTRY]          VARCHAR (30) DEFAULT (' ') NOT NULL,
    [AREACODE]         VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [EXCHCODE]         VARCHAR (3)  DEFAULT (' ') NOT NULL,
    [PHONENUM]         VARCHAR (4)  DEFAULT (' ') NOT NULL,
    [PHONE_NUM]        VARCHAR (20) DEFAULT (' ') NOT NULL,
    [EMPL_ENTERED]     VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [FIRST_OWNER]      VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [CONTACT]          VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [EMAIL]            VARCHAR (60) DEFAULT (' ') NOT NULL,
    [GENDER]           VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [MARITALSTATUS]    VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [AGE]              VARCHAR (10) DEFAULT (' ') NOT NULL,
    [PURCHFOR1]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [PURCHFOR2]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [PURCHFOR3]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [PURCHFOR4]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [PURCHFOR5]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [PURCHFOR6]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [PURCHFOR7]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [PURCHFOR8]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [PURCHFOR9]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [LEARNEDFROM1]     VARCHAR (30) DEFAULT (' ') NOT NULL,
    [LEARNEDFROM2]     VARCHAR (30) DEFAULT (' ') NOT NULL,
    [LEARNEDFROM3]     VARCHAR (30) DEFAULT (' ') NOT NULL,
    [LEARNEDFROM4]     VARCHAR (50) DEFAULT (' ') NOT NULL,
    [LEARNEDFROM5]     VARCHAR (50) DEFAULT (' ') NOT NULL,
    [LEARNEDFROM6]     VARCHAR (50) DEFAULT (' ') NOT NULL,
    [ACT_DATE]         DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [PUR_DATE]         DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [OWN_SA_PROD]      VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [OWN_M1A]          VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [OWN_1911]         VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [OWN_XD]           VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [OWN_M1G]          VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [OWN_XDM]          VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [INCOME]           VARCHAR (20) DEFAULT (' ') NOT NULL,
    [DECISION1]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [DECISION2]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [DECISION3]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [DECISION4]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [DECISION5]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [DECISION6]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [DECISION7]        VARCHAR (30) DEFAULT (' ') NOT NULL,
    [OCCUPATION]       VARCHAR (50) DEFAULT (' ') NOT NULL,
    [CONF_NUM]         DECIMAL (14) DEFAULT ((0)) NOT NULL,
    [EMPL_UNAME]       VARCHAR (20) DEFAULT (' ') NOT NULL,
    [ACTIVATIONNUM]    DECIMAL (14) DEFAULT ((0)) NOT NULL,
    [BIRTHDATE]        DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    [Own_XDS]          VARCHAR (1)  DEFAULT (' ') NOT NULL,
    [CreatedBy]        VARCHAR (20) NULL,
    [CreatedOn]        DATETIME     CONSTRAINT [D_dbo_WARRANTY_1] DEFAULT (getdate()) NULL,
    [Duplicate]        TINYINT      DEFAULT ((0)) NOT NULL,
    [SentEmail]        VARCHAR (1)  NULL,
    [HubSpotContactID] BIGINT       DEFAULT ((0)) NOT NULL,
    [OWN_SAINT]        VARCHAR (1)  NULL,
    CONSTRAINT [WARRANTY_INDEX01] PRIMARY KEY CLUSTERED ([SERIALNUM] ASC, [Duplicate] ASC, [SPRNUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70)
);








GO
CREATE UNIQUE NONCLUSTERED INDEX [WARRANTY_INDEX00]
    ON [dbo].[WARRANTY]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WARRANTY_INDEX02]
    ON [dbo].[WARRANTY]([SERIALNUM] ASC, [Duplicate] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WARRANTY_INDEX03]
    ON [dbo].[WARRANTY]([ZIP] ASC, [FIRST_NAME] ASC, [LAST_NAME] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WARRANTY_INDEX04]
    ON [dbo].[WARRANTY]([CONF_NUM] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WARRANTY_INDEX05]
    ON [dbo].[WARRANTY]([FIRST_NAME] ASC, [LAST_NAME] ASC, [SERIALNUM] ASC, [Duplicate] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WARRANTY_INDEX06]
    ON [dbo].[WARRANTY]([LAST_NAME] ASC, [FIRST_NAME] ASC, [SERIALNUM] ASC, [Duplicate] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WARRANTY_INDEX08]
    ON [dbo].[WARRANTY]([EMAIL] ASC, [PUR_DATE] ASC, [Recnum] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [WARRANTY_INDEX07]
    ON [dbo].[WARRANTY]([HubSpotContactID] ASC, [Recnum] ASC);

