CREATE TABLE [dbo].[GLUser] (
    [Recnum]        BIGINT       IDENTITY (1, 1) NOT NULL,
    [ID]            DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [LOGIN]         VARCHAR (10) DEFAULT (' ') NOT NULL,
    [GLCOMPAN_ID]   DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [GLCOMPAN_Name] VARCHAR (30) DEFAULT (' ') NOT NULL,
    [APCOMPAN_ID]   DECIMAL (10) DEFAULT ((0)) NOT NULL,
    [APCOMPAN_NAME] VARCHAR (30) DEFAULT (' ') NOT NULL,
    [DATE_TODAY]    DATETIME     DEFAULT ('01/01/1753') NOT NULL,
    CONSTRAINT [GLUser_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLUser_INDEX00]
    ON [dbo].[GLUser]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLUser_INDEX02]
    ON [dbo].[GLUser]([LOGIN] ASC) WITH (FILLFACTOR = 70);

