CREATE TABLE [dbo].[cmacctyp] (
    [Recnum]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [ACCTYPE]        VARCHAR (1)    DEFAULT (' ') NOT NULL,
    [DESCRIPTION]    VARCHAR (30)   DEFAULT (' ') NOT NULL,
    [DISCOUNT_PRCNT] DECIMAL (4, 2) DEFAULT ((0)) NOT NULL,
    [DISCOUNT_DAYS]  DECIMAL (4)    DEFAULT ((0)) NOT NULL,
    [NET_DAYS]       DECIMAL (4)    DEFAULT ((0)) NOT NULL,
    CONSTRAINT [cmacctyp_INDEX01] PRIMARY KEY CLUSTERED ([ACCTYPE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [cmacctyp_INDEX00]
    ON [dbo].[cmacctyp]([Recnum] ASC) WITH (FILLFACTOR = 70);

