CREATE TABLE [dbo].[FedBkALD] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [GUNTYPE]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SERIAL]      VARCHAR (14)    DEFAULT (' ') NOT NULL,
    [RECEIVED]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [MANUFACT]    VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [MODEL]       VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [SEMIFULL]    VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [NAME]        VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [STREET]      VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [CITY]        VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [STATE]       VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [SPRNUM]      VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [GUNMODEL]    VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [SOLD]        DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [SONAME]      VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [SOSTREET]    VARCHAR (35)    CONSTRAINT [DF__FedBkALD__SOSTRE__5E385EAF] DEFAULT (' ') NOT NULL,
    [SOCITY]      VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [SOSTATE]     VARCHAR (2)     DEFAULT (' ') NOT NULL,
    [SOLDFFL]     VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [ORDNUM]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [TAG]         VARCHAR (6)     DEFAULT (' ') NOT NULL,
    [SAFETY]      VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [GUNSMITH]    VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [TAGNUM]      DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [FEDCODE]     VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [CALIBER]     VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [WO_NUMBER]   DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [COMMENT]     VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [RCTICKET]    DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [BAN_STATUS]  VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [LOCATION]    VARCHAR (20)    DEFAULT (' ') NOT NULL,
    [CHANGE_FLAG] VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [INITIALS]    VARCHAR (10)    DEFAULT (' ') NOT NULL,
    [NOTES]       VARCHAR (60)    DEFAULT (' ') NOT NULL,
    [CreatedBy]   VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [CreatedDate] DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]   VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [ChangedDate] DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [Version]     VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [OrderSeq]    DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [Form4473]    DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [ManuFFL]     VARCHAR (10)    DEFAULT (' ') NOT NULL,
    CONSTRAINT [FedBkALD_INDEX01] PRIMARY KEY CLUSTERED ([GUNTYPE] ASC, [SERIAL] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_FedBkALD_FEDCODE] FOREIGN KEY ([FEDCODE]) REFERENCES [dbo].[FEDCODE] ([GROUP_CODE]),
    CONSTRAINT [FK_FedBkALD_SPRNUM] FOREIGN KEY ([SPRNUM]) REFERENCES [dbo].[parts] ([SPRNUM])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX00]
    ON [dbo].[FedBkALD]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX02]
    ON [dbo].[FedBkALD]([ORDNUM] ASC, [GUNTYPE] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX03]
    ON [dbo].[FedBkALD]([TAGNUM] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX04]
    ON [dbo].[FedBkALD]([RCTICKET] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX05]
    ON [dbo].[FedBkALD]([SONAME] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX06]
    ON [dbo].[FedBkALD]([SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX07]
    ON [dbo].[FedBkALD]([GUNTYPE] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX08]
    ON [dbo].[FedBkALD]([SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX09]
    ON [dbo].[FedBkALD]([GUNTYPE] ASC, [SOLD] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX11]
    ON [dbo].[FedBkALD]([NAME] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FedBkALD_INDEX12]
    ON [dbo].[FedBkALD]([ORDNUM] ASC, [SPRNUM] ASC, [OrderSeq] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

