CREATE TABLE [dbo].[GLDISWRK] (
    [Recnum]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [DIVISION_ID]   VARCHAR (4)     DEFAULT (' ') NOT NULL,
    [GL_ACCT_NUMB]  VARCHAR (5)     DEFAULT (' ') NOT NULL,
    [PERIOD_#]      DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [FLAG]          VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [SOURCE]        VARCHAR (3)     DEFAULT (' ') NOT NULL,
    [TRANS_DATE]    DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [DEBIT_AMOUNT]  DECIMAL (12, 2) NOT NULL,
    [CREDIT_AMOUNT] DECIMAL (12, 2) NOT NULL,
    [REFERENCE]     VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [VENDOR_#]      VARCHAR (8)     DEFAULT (' ') NOT NULL,
    [INVOICE_#]     VARCHAR (15)    DEFAULT (' ') NOT NULL,
    [PAID_DATE]     DATETIME        DEFAULT ('01/01/1753') NOT NULL,
    [CHECKNUM]      DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [BATCH_#]       DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [PO_#]          DECIMAL (6)     DEFAULT ((0)) NOT NULL,
    [PO_LINE_#]     DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [DESCRIPTION]   VARCHAR (25)    DEFAULT (' ') NOT NULL,
    [ID]            DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [GLMASTER_ID]   DECIMAL (10)    DEFAULT ((0)) NOT NULL,
    [DIVACCT]       VARCHAR (5)     DEFAULT (' ') NOT NULL,
    CONSTRAINT [GLDISWRK_INDEX01] PRIMARY KEY CLUSTERED ([DIVISION_ID] ASC, [GL_ACCT_NUMB] ASC, [PERIOD_#] ASC, [BATCH_#] ASC, [FLAG] ASC, [VENDOR_#] ASC, [INVOICE_#] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70),
    CONSTRAINT [FK_GLDISWRK_GLMASTER_ID] FOREIGN KEY ([GLMASTER_ID]) REFERENCES [dbo].[GLMASTER] ([ID])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLDISWRK_INDEX00]
    ON [dbo].[GLDISWRK]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLDISWRK_INDEX02]
    ON [dbo].[GLDISWRK]([ID] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [GLDISWRK_INDEX03]
    ON [dbo].[GLDISWRK]([GLMASTER_ID] ASC, [ID] ASC) WITH (FILLFACTOR = 70);

