CREATE TABLE [stage].[CustomerOrder] (
    [ID]                BIGINT          IDENTITY (1, 1) NOT NULL,
    [BillToCustomerKey] BIGINT          DEFAULT ((0)) NOT NULL,
    [BillToLocationKey] BIGINT          DEFAULT ((0)) NOT NULL,
    [ShipToCustomerKey] BIGINT          DEFAULT ((0)) NOT NULL,
    [ShipToLocationKey] BIGINT          DEFAULT ((0)) NOT NULL,
    [OrderDateKey]      BIGINT          DEFAULT ((0)) NOT NULL,
    [ShipDateKey]       BIGINT          DEFAULT ((0)) NOT NULL,
    [WantedDateKey]     BIGINT          DEFAULT ((0)) NOT NULL,
    [PartKey]           BIGINT          DEFAULT ((0)) NOT NULL,
    [SourceOrderRecnum] BIGINT          DEFAULT ((0)) NOT NULL,
    [SourceLineRecnum]  BIGINT          DEFAULT ((0)) NOT NULL,
    [ShipToName]        VARCHAR (36)    DEFAULT ('') NOT NULL,
    [OrderNumber]       DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [OrderStatus]       CHAR (2)        DEFAULT ('') NOT NULL,
    [LineItemNumber]    DECIMAL (4)     DEFAULT ((0)) NOT NULL,
    [LineItemStatus]    CHAR (1)        DEFAULT ('') NOT NULL,
    [CustomerPO]        VARCHAR (40)    DEFAULT ('') NOT NULL,
    [ShipToPO]          VARCHAR (40)    DEFAULT ('') NOT NULL,
    [PaidDate]          DATETIME        DEFAULT (getdate()) NOT NULL,
    [CancelDate]        DATETIME        DEFAULT (getdate()) NOT NULL,
    [SubtotalAmount]    DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [DiscountAmount]    DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [PostageAmount]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [DepositAmount]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [CODAmount]         DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [TaxAmount]         DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [ReceivedAmount]    DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [TotalAmount]       DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [BalanceAmount]     DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [RefundAmount]      DECIMAL (10, 2) DEFAULT ((0)) NOT NULL,
    [UnitPrice]         DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [TotalPrice]        DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [RegularPrice]      DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [ListPrice]         DECIMAL (8, 2)  DEFAULT ((0)) NOT NULL,
    [TotalCost]         DECIMAL (10, 4) DEFAULT ((0)) NOT NULL,
    [UnitRawCost]       DECIMAL (12, 6) DEFAULT ((0)) NOT NULL,
    [UnitFinalCost]     DECIMAL (12, 6) DEFAULT ((0)) NOT NULL,
    [ItemQuantity]      DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [ShippedQuantity]   DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [BackorderQuantity] DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [QuanS]             DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [Quan_BO]           DECIMAL (8)     DEFAULT ((0)) NOT NULL,
    [YardCode]          VARCHAR (4)     DEFAULT ('') NOT NULL,
    [Programming_Ver]   DECIMAL (2)     DEFAULT ((0)) NOT NULL,
    [DWChecksum]        AS              (CONVERT([binary](32),hashbytes('SHA2_256',(((((((((((((((((((((((((((((((((((((((((CONVERT([varchar](32),[BillToCustomerKey])+CONVERT([varchar](32),[BillToLocationKey]))+CONVERT([varchar](32),[ShipToCustomerKey]))+CONVERT([varchar](32),[ShipToLocationKey]))+CONVERT([varchar](32),[OrderDateKey]))+CONVERT([varchar](32),[ShipDateKey]))+CONVERT([varchar](32),[WantedDateKey]))+CONVERT([varchar](32),[PartKey]))+CONVERT([varchar](32),[SourceOrderRecnum]))+CONVERT([varchar](32),[SourceLineRecnum]))+[ShipToName])+CONVERT([varchar](20),[OrderNumber]))+[OrderStatus])+CONVERT([varchar](20),[LineItemNumber]))+[LineItemStatus])+[CustomerPO])+[ShipToPO])+CONVERT([varchar](20),[PaidDate]))+CONVERT([varchar](20),[CancelDate]))+CONVERT([varchar](20),[SubtotalAmount]))+CONVERT([varchar](20),[DiscountAmount]))+CONVERT([varchar](20),[PostageAmount]))+CONVERT([varchar](20),[DepositAmount]))+CONVERT([varchar](20),[CODAmount]))+CONVERT([varchar](20),[TaxAmount]))+CONVERT([varchar](20),[ReceivedAmount]))+CONVERT([varchar](20),[TotalAmount]))+CONVERT([varchar](20),[BalanceAmount]))+CONVERT([varchar](20),[RefundAmount]))+CONVERT([varchar](20),[UnitPrice]))+CONVERT([varchar](20),[TotalPrice]))+CONVERT([varchar](20),[RegularPrice]))+CONVERT([varchar](20),[ListPrice]))+CONVERT([varchar](20),[TotalCost]))+CONVERT([varchar](20),[UnitRawCost]))+CONVERT([varchar](20),[UnitFinalCost]))+CONVERT([varchar](20),[ItemQuantity]))+CONVERT([varchar](20),[ShippedQuantity]))+CONVERT([varchar](20),[BackorderQuantity]))+CONVERT([varchar](20),[QuanS]))+CONVERT([varchar](20),[Quan_BO]))+[YardCode])+CONVERT([varchar](20),[Programming_Ver])))),
    CONSTRAINT [pk_CustomerOrder] PRIMARY KEY CLUSTERED ([ID] ASC)
);

