CREATE TABLE [stage].[CMASTER] (
    [Recnum]                BIGINT          NULL,
    [CUSTID]                VARCHAR (10)    NOT NULL,
    [BNAME]                 VARCHAR (36)    NULL,
    [BSTREET]               VARCHAR (35)    NULL,
    [BSTREET2]              VARCHAR (35)    NULL,
    [BCITY]                 VARCHAR (30)    NULL,
    [BSTATE]                VARCHAR (2)     NULL,
    [BZIP]                  VARCHAR (10)    NULL,
    [COUNTRY]               VARCHAR (15)    NULL,
    [FFLEXPR]               DATETIME        NULL,
    [ACCTYPE]               VARCHAR (1)     NULL,
    [CLASS]                 VARCHAR (1)     NULL,
    [CONTACT_NAME_1]        VARCHAR (36)    NULL,
    [PHONE]                 VARCHAR (10)    NULL,
    [CONTACT_NAME_2]        VARCHAR (36)    NULL,
    [PHONE_2]               VARCHAR (10)    NULL,
    [FAX_NUMBER]            VARCHAR (10)    NULL,
    [ILLTAX]                VARCHAR (12)    NULL,
    [YTDSHIP]               DECIMAL (12, 2) NULL,
    [YTDPAY]                DECIMAL (12, 2) NULL,
    [TELESTAT]              VARCHAR (2)     NULL,
    [TELEWHO]               VARCHAR (4)     NULL,
    [FFLNUM]                VARCHAR (10)    NULL,
    [LPAYOPEN]              DATETIME        NULL,
    [LPAYCOD]               DATETIME        NULL,
    [STOCKING]              VARCHAR (1)     NULL,
    [EXCISE_FLAG]           VARCHAR (1)     NULL,
    [DISCOUNT]              DECIMAL (4, 2)  NULL,
    [TIME_ZONE]             DECIMAL (2)     NULL,
    [TERMS]                 VARCHAR (15)    NULL,
    [GROUP_CODE]            VARCHAR (10)    NULL,
    [PROF_GUNSMITH]         DATETIME        NULL,
    [MATCH_FLAG]            VARCHAR (1)     NULL,
    [DL_NUMBER]             VARCHAR (25)    NULL,
    [DL_STATE]              VARCHAR (2)     NULL,
    [CUSTYPE]               VARCHAR (1)     NULL,
    [NOW]                   DECIMAL (10, 2) NULL,
    [OTHIRTY]               DECIMAL (10, 2) NULL,
    [OSIXTY]                DECIMAL (10, 2) NULL,
    [ONINETY]               DECIMAL (10, 2) NULL,
    [O1TWENTY]              DECIMAL (10, 2) NULL,
    [FINANCE]               DECIMAL (10, 2) NULL,
    [LASTCALC]              DATETIME        NULL,
    [FIRSTPUR]              DATETIME        NULL,
    [HICREDIT]              DECIMAL (10, 2) NULL,
    [CRLIMIT]               DECIMAL (10, 2) NULL,
    [TOTPAID]               DECIMAL (6)     NULL,
    [PAIDNOW]               DECIMAL (6)     NULL,
    [PAID30]                DECIMAL (6)     NULL,
    [PAID60]                DECIMAL (6)     NULL,
    [PAID90]                DECIMAL (6)     NULL,
    [PAID120]               DECIMAL (6)     NULL,
    [INTRATE]               DECIMAL (6, 4)  NULL,
    [WFINANCE]              DECIMAL (10, 2) NULL,
    [CURBAL]                DECIMAL (10, 2) NULL,
    [N1]                    VARCHAR (35)    NULL,
    [N2]                    VARCHAR (35)    NULL,
    [N3]                    VARCHAR (35)    NULL,
    [N4]                    VARCHAR (35)    NULL,
    [N5]                    VARCHAR (35)    NULL,
    [LABEL_FLAG]            VARCHAR (1)     NULL,
    [YTDBILL]               DECIMAL (12, 2) NULL,
    [DELETE_FLAG]           VARCHAR (1)     NULL,
    [MEDIA_CODE]            VARCHAR (6)     NULL,
    [ACCRUAL_DISC]          DECIMAL (6, 2)  NULL,
    [SALES_TAX_DATE]        DATETIME        NULL,
    [EXCISE_#]              VARCHAR (20)    NULL,
    [EXCISE_DATE]           DATETIME        NULL,
    [CREDIT_DATE]           DATETIME        NULL,
    [STATEID]               VARCHAR (4)     NULL,
    [EMAIL]                 VARCHAR (35)    NULL,
    [REP_ID]                VARCHAR (15)    NULL,
    [SA_REP]                VARCHAR (15)    NULL,
    [ADDED_REP]             VARCHAR (15)    NULL,
    [DATE_ADDED]            DATETIME        NULL,
    [TOTALAMOUNTDUE]        DECIMAL (10, 2) NULL,
    [PAIDCURRENTPER]        DECIMAL (6, 2)  NULL,
    [PAID30PER]             DECIMAL (6, 2)  NULL,
    [PAID60PER]             DECIMAL (6, 2)  NULL,
    [PAID90PER]             DECIMAL (6, 2)  NULL,
    [PAID120PER]            DECIMAL (6, 2)  NULL,
    [ONMAILING_FLAG]        VARCHAR (1)     NULL,
    [APPLYSHIPPING]         VARCHAR (1)     NULL,
    [WEBSITE]               VARCHAR (80)    NULL,
    [LAST_NAME]             VARCHAR (25)    NULL,
    [FIRST_NAME]            VARCHAR (15)    NULL,
    [Customer_Type]         VARCHAR (1)     NULL,
    [TAX_FORM_EXP]          DATETIME        NULL,
    [USERINITIALS]          VARCHAR (4)     NULL,
    [DUE_0_20]              DECIMAL (12, 2) NULL,
    [DUE_21_30]             DECIMAL (12, 2) NULL,
    [DUE_31_45]             DECIMAL (12, 2) NULL,
    [DUE_46_60]             DECIMAL (12, 2) NULL,
    [DUE_60PLUS]            DECIMAL (12, 2) NULL,
    [PriceType]             VARCHAR (20)    NULL,
    [DefaultPrice]          VARCHAR (1)     NULL,
    [EMailInvoice]          VARCHAR (1)     NULL,
    [EMailMerge]            VARCHAR (1)     NULL,
    [EMailSubject]          VARCHAR (80)    NULL,
    [CreatedBy]             VARCHAR (4)     NULL,
    [CreatedDate]           DATE            NULL,
    [ChangedBy]             VARCHAR (4)     NULL,
    [ChangedDate]           DATE            NULL,
    [Version]               VARCHAR (15)    NULL,
    [BuyGroup]              VARCHAR (1)     NULL,
    [BuyGroupNum]           BIGINT          NULL,
    [OptInRecallEmails]     VARCHAR (1)     NULL,
    [OptInEmails]           VARCHAR (1)     NULL,
    [OptInRecallEmailsDate] DATETIME        NULL,
    [OptInEmailsDate]       DATETIME        NULL,
    [ExternalCustID]        BIGINT          NULL,
    [ShipDestinationType]   VARCHAR (1)     NULL,
    [Hold]                  VARCHAR (1)     NULL,
    [HoldDate]              DATETIME        NULL,
    [HoldReason]            VARCHAR (256)   NULL,
    [PostType]              VARCHAR (2)     NULL,
    [ShipUPS]               VARCHAR (1)     NULL,
    [HoldBy]                VARCHAR (4)     NULL,
    [ShipApprovalRequired]  VARCHAR (1)     NULL,
    [ExternalCustType]      VARCHAR (1)     NULL,
    [AssuredDiscount]       NUMERIC (6, 4)  NULL,
    [ADToDiscountedOnly]    VARCHAR (1)     NULL,
    CONSTRAINT [pk_CMASTER] PRIMARY KEY CLUSTERED ([CUSTID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CMASTER_INDEX00]
    ON [stage].[CMASTER]([CUSTID] ASC)
    INCLUDE([BNAME], [BCITY], [BSTATE], [COUNTRY]);

