CREATE TABLE [stage].[CUSTINFO] (
    [Recnum]              BIGINT          NULL,
    [BCUSTID]             VARCHAR (10)    NULL,
    [SCUSTID]             VARCHAR (10)    NULL,
    [DATE]                DATETIME        NULL,
    [SHIPDATE]            DATETIME        NULL,
    [ORDNUM]              DECIMAL (10, 2) NOT NULL,
    [COM]                 VARCHAR (1)     NULL,
    [SNAME]               VARCHAR (36)    NULL,
    [SUB]                 DECIMAL (10, 2) NULL,
    [DISC]                DECIMAL (8, 2)  NULL,
    [POST]                DECIMAL (8, 2)  NULL,
    [DEP]                 DECIMAL (8, 2)  NULL,
    [COD]                 DECIMAL (6, 2)  NULL,
    [TAX]                 DECIMAL (8, 2)  NULL,
    [RECEIVED]            DECIMAL (8, 2)  NULL,
    [CARDKIND]            VARCHAR (1)     NULL,
    [CARDNUM]             VARCHAR (19)    NULL,
    [N1]                  VARCHAR (35)    NULL,
    [N2]                  VARCHAR (35)    NULL,
    [N3]                  VARCHAR (35)    NULL,
    [N4]                  VARCHAR (35)    NULL,
    [N5]                  VARCHAR (35)    NULL,
    [N6]                  VARCHAR (35)    NULL,
    [N7]                  VARCHAR (35)    NULL,
    [STATUS]              VARCHAR (2)     NULL,
    [ACCTYPE]             VARCHAR (1)     NULL,
    [EXPIRE]              VARCHAR (4)     NULL,
    [EXCISE_FLAG]         VARCHAR (1)     NULL,
    [CHECK_TYPE]          VARCHAR (1)     NULL,
    [EXCISE_DATE]         DATETIME        NULL,
    [PAID_DATE]           DATETIME        NULL,
    [LAST_CHANGE]         DECIMAL (4)     NULL,
    [ORIGINAL]            DECIMAL (8)     NULL,
    [DATE_WANTED]         DATETIME        NULL,
    [CANCEL_DATE]         DATETIME        NULL,
    [OVER60_FLAG]         VARCHAR (1)     NULL,
    [OTOTAL]              DECIMAL (10, 2) NULL,
    [BACKORDER]           VARCHAR (1)     NULL,
    [CUST_PO#]            VARCHAR (40)    NULL,
    [TAXRATE]             DECIMAL (6, 4)  NULL,
    [TRADE_AMOUNT]        DECIMAL (8, 2)  NULL,
    [TRADE_TAX_FLAG]      VARCHAR (1)     NULL,
    [COMPANY_#]           VARCHAR (4)     NULL,
    [ACCR_DISC]           DECIMAL (6, 2)  NULL,
    [WHLE_DISC]           DECIMAL (8, 2)  NULL,
    [STATEID]             VARCHAR (4)     NULL,
    [TELEWHO]             VARCHAR (4)     NULL,
    [FREIGHT_FLAG]        VARCHAR (1)     NULL,
    [COD_FLAG]            VARCHAR (1)     NULL,
    [CID]                 VARCHAR (5)     NULL,
    [StoreSale_Flag]      VARCHAR (1)     NULL,
    [YardCode]            VARCHAR (4)     NULL,
    [Packing_Notes]       VARCHAR (MAX)   NULL,
    [Balance]             DECIMAL (10, 2) NULL,
    [RefundTotal]         DECIMAL (10, 2) NULL,
    [Invoice_Notes]       VARCHAR (MAX)   NULL,
    [Programming_Ver]     DECIMAL (2)     NULL,
    [Sub_Taxable]         DECIMAL (10, 2) NULL,
    [OrderedBy]           VARCHAR (30)    NULL,
    [Date_Due]            DATETIME        NULL,
    [O_Sub]               DECIMAL (10, 2) NULL,
    [O_Disc]              DECIMAL (10, 2) NULL,
    [O_Post]              DECIMAL (10, 2) NULL,
    [O_Tax]               DECIMAL (10, 2) NULL,
    [O_SubTaxable]        DECIMAL (10, 2) NULL,
    [O_Total]             DECIMAL (10, 2) NULL,
    [SUBTOT]              DECIMAL (10, 2) NULL,
    [USERINITIALS]        VARCHAR (4)     NULL,
    [ShippedBy]           VARCHAR (4)     NULL,
    [TaxStateRate]        DECIMAL (6, 4)  NULL,
    [TaxCountyRate]       DECIMAL (6, 4)  NULL,
    [TaxCityRate]         DECIMAL (6, 4)  NULL,
    [TaxSpecialRate]      DECIMAL (6, 4)  NULL,
    [TaxByZipID]          DECIMAL (10)    NULL,
    [InvoiceNum]          DECIMAL (8)     NULL,
    [ShipToPO]            VARCHAR (40)    NULL,
    [Form4473]            DECIMAL (8)     NULL,
    [CalcTax]             VARCHAR (1)     NULL,
    [CreatedBy]           VARCHAR (4)     NULL,
    [CreatedDate]         DATETIME        NULL,
    [ChangedBy]           VARCHAR (4)     NULL,
    [ChangedDate]         DATETIME        NULL,
    [Version]             VARCHAR (15)    NULL,
    [ForceTax]            VARCHAR (1)     NULL,
    [NoPLPrint]           VARCHAR (1)     NULL,
    [ReleaseDate]         DATETIME        NULL,
    [SAddress]            VARCHAR (35)    NULL,
    [SAddress2]           VARCHAR (35)    NULL,
    [SCity]               VARCHAR (30)    NULL,
    [SState]              VARCHAR (2)     NULL,
    [SZip]                VARCHAR (10)    NULL,
    [SCountry]            VARCHAR (2)     NULL,
    [ExternalOrderType]   VARCHAR (1)     NULL,
    [ExternalOrdNum]      BIGINT          NULL,
    [CCToken]             VARCHAR (25)    NULL,
    [CCApprovalCode]      VARCHAR (25)    NULL,
    [NoTaxChange]         VARCHAR (1)     NULL,
    [CCRetRef]            VARCHAR (25)    NULL,
    [Sub_Labor]           NUMERIC (10, 2) NULL,
    [Sub_LaborRepair]     NUMERIC (10, 2) NULL,
    [Sub_Apparel]         NUMERIC (10, 2) NULL,
    [CouponDiscount]      NUMERIC (6, 2)  NULL,
    [ReadyToShip]         VARCHAR (4)     NULL,
    [PostType]            VARCHAR (2)     NULL,
    [ShipDestinationType] VARCHAR (1)     NULL,
    [ShipUPS]             VARCHAR (1)     NULL,
    [IAS_Sub]             NUMERIC (10, 2) NULL,
    [IAS_Disc]            NUMERIC (10, 2) NULL,
    [IAS_Post]            NUMERIC (10, 2) NULL,
    [IAS_Tax]             NUMERIC (10, 2) NULL,
    [IAS_OTotal]          NUMERIC (10, 2) NULL,
    [IAS_Sub_Taxable]     NUMERIC (10, 2) NULL,
    [IAS_Sub_Labor]       NUMERIC (10, 2) NULL,
    [IAS_Sub_LaborRepair] NUMERIC (10, 2) NULL,
    [IAS_Sub_Apparel]     NUMERIC (10, 2) NULL,
    [NumberOfCartons]     SMALLINT        NULL,
    [Packed]              VARCHAR (4)     NULL,
    [ShipLocation]        VARCHAR (1)     NULL,
    [CustApproval]        VARCHAR (1)     NULL,
    [MgrApproval]         VARCHAR (1)     NULL,
    [ReadyToShipDate]     DATETIME        NULL,
    [CancelAfter]         DATETIME        NULL,
    [AuthorizedAmount]    NUMERIC (10, 2) NULL,
    [AVSResult]           VARCHAR (1)     NULL,
    [CCTranStatus]        VARCHAR (1)     NULL,
    [CCLatestTransID]     VARCHAR (25)    NULL,
    [AdultSig]            VARCHAR (1)     NULL,
    CONSTRAINT [pk_CUSTINFO] PRIMARY KEY CLUSTERED ([ORDNUM] ASC)
);

