CREATE TABLE [stage].[MASTERLN] (
    [Recnum]          BIGINT          NULL,
    [ORDNUM]          DECIMAL (10, 2) NOT NULL,
    [QUAN]            DECIMAL (8)     NULL,
    [QUANS]           DECIMAL (8)     NULL,
    [SPRNUM]          VARCHAR (20)    NULL,
    [DESC]            VARCHAR (38)    NULL,
    [UPRICE]          DECIMAL (8, 2)  NULL,
    [TPRICE]          DECIMAL (8, 2)  NULL,
    [BACKORDER]       VARCHAR (1)     NULL,
    [QUANSHIP]        DECIMAL (8)     NULL,
    [DATE]            DATETIME        NULL,
    [SHIPDATE]        DATETIME        NULL,
    [IN]              DECIMAL (4)     NOT NULL,
    [YARD]            VARCHAR (4)     NULL,
    [COM]             VARCHAR (1)     NULL,
    [TELEYARD]        VARCHAR (4)     NULL,
    [EXCISE_DATE]     DATETIME        NULL,
    [IN2]             DECIMAL (2)     NULL,
    [TCOST]           DECIMAL (10, 4) NULL,
    [REGPRICE]        DECIMAL (8, 2)  NULL,
    [BACKREL]         DECIMAL (8)     NULL,
    [LIST_PRICE]      DECIMAL (8, 2)  NULL,
    [CUSTOM_FLAG]     VARCHAR (1)     NULL,
    [Quan_BO]         DECIMAL (8)     NULL,
    [Status]          VARCHAR (1)     NULL,
    [Programming_Ver] DECIMAL (2)     NULL,
    [Purchase_Time]   VARCHAR (5)     NULL,
    [RawCostEach]     DECIMAL (12, 6) NULL,
    [FinCostEach]     DECIMAL (12, 6) NULL,
    [USERINITIALS]    VARCHAR (4)     NULL,
    [MovedToBO]       VARCHAR (1)     NULL,
    [QuanA]           INT             NULL,
    [QuanPacked]      DECIMAL (8)     NULL,
    [QuanSOriginal]   INT             NULL,
    CONSTRAINT [pk_MASTERLN] PRIMARY KEY CLUSTERED ([ORDNUM] ASC, [IN] ASC)
);

