CREATE TABLE [dbo].[OrderHeaderHistory] (
    [ID]                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [Recnum]                   BIGINT          NOT NULL,
    [BCUSTID]                  VARCHAR (10)    NOT NULL,
    [SCUSTID]                  VARCHAR (10)    NOT NULL,
    [DATE]                     DATETIME        NOT NULL,
    [SHIPDATE]                 DATETIME        NOT NULL,
    [ORDNUM]                   DECIMAL (10, 2) NOT NULL,
    [COM]                      VARCHAR (1)     NOT NULL,
    [SNAME]                    VARCHAR (36)    NOT NULL,
    [SUB]                      DECIMAL (10, 2) NOT NULL,
    [DISC]                     DECIMAL (8, 2)  NOT NULL,
    [POST]                     DECIMAL (8, 2)  NOT NULL,
    [DEP]                      DECIMAL (8, 2)  NOT NULL,
    [COD]                      DECIMAL (6, 2)  NOT NULL,
    [TAX]                      DECIMAL (8, 2)  NOT NULL,
    [RECEIVED]                 DECIMAL (8, 2)  NOT NULL,
    [CARDKIND]                 VARCHAR (1)     NOT NULL,
    [CARDNUM]                  VARCHAR (19)    NOT NULL,
    [N1]                       VARCHAR (35)    NOT NULL,
    [N2]                       VARCHAR (35)    NOT NULL,
    [N3]                       VARCHAR (35)    NOT NULL,
    [N4]                       VARCHAR (35)    NOT NULL,
    [N5]                       VARCHAR (35)    NOT NULL,
    [N6]                       VARCHAR (35)    NOT NULL,
    [N7]                       VARCHAR (35)    NOT NULL,
    [STATUS]                   VARCHAR (2)     NOT NULL,
    [ACCTYPE]                  VARCHAR (1)     NOT NULL,
    [EXPIRE]                   VARCHAR (4)     NOT NULL,
    [EXCISE_FLAG]              VARCHAR (1)     NOT NULL,
    [CHECK_TYPE]               VARCHAR (1)     NOT NULL,
    [EXCISE_DATE]              DATETIME        NOT NULL,
    [PAID_DATE]                DATETIME        NOT NULL,
    [LAST_CHANGE]              DECIMAL (4)     NOT NULL,
    [ORIGINAL]                 DECIMAL (8)     NOT NULL,
    [DATE_WANTED]              DATETIME        NOT NULL,
    [CANCEL_DATE]              DATETIME        NOT NULL,
    [OVER60_FLAG]              VARCHAR (1)     NOT NULL,
    [OTOTAL]                   DECIMAL (10, 2) NOT NULL,
    [BACKORDER]                VARCHAR (1)     NOT NULL,
    [CUST_PO#]                 VARCHAR (40)    NOT NULL,
    [TAXRATE]                  DECIMAL (6, 4)  NOT NULL,
    [TRADE_AMOUNT]             DECIMAL (8, 2)  NOT NULL,
    [TRADE_TAX_FLAG]           VARCHAR (1)     NOT NULL,
    [COMPANY_#]                VARCHAR (4)     NOT NULL,
    [ACCR_DISC]                DECIMAL (6, 2)  NOT NULL,
    [WHLE_DISC]                DECIMAL (8, 2)  NOT NULL,
    [STATEID]                  VARCHAR (4)     NOT NULL,
    [TELEWHO]                  VARCHAR (4)     NOT NULL,
    [FREIGHT_FLAG]             VARCHAR (1)     NOT NULL,
    [COD_FLAG]                 VARCHAR (1)     NOT NULL,
    [CID]                      VARCHAR (5)     NOT NULL,
    [StoreSale_Flag]           VARCHAR (1)     NOT NULL,
    [YardCode]                 VARCHAR (4)     NOT NULL,
    [Packing_Notes]            VARCHAR (MAX)   NULL,
    [Balance]                  DECIMAL (10, 2) NOT NULL,
    [RefundTotal]              DECIMAL (10, 2) NOT NULL,
    [Invoice_Notes]            VARCHAR (MAX)   NULL,
    [Programming_Ver]          DECIMAL (2)     NOT NULL,
    [Sub_Taxable]              DECIMAL (10, 2) NOT NULL,
    [OrderedBy]                VARCHAR (30)    NOT NULL,
    [Date_Due]                 DATETIME        NOT NULL,
    [O_Sub]                    DECIMAL (10, 2) NOT NULL,
    [O_Disc]                   DECIMAL (10, 2) NOT NULL,
    [O_Post]                   DECIMAL (10, 2) NOT NULL,
    [O_Tax]                    DECIMAL (10, 2) NOT NULL,
    [O_SubTaxable]             DECIMAL (10, 2) NOT NULL,
    [O_Total]                  DECIMAL (10, 2) NOT NULL,
    [SUBTOT]                   DECIMAL (10, 2) NOT NULL,
    [USERINITIALS]             VARCHAR (4)     NOT NULL,
    [ShippedBy]                VARCHAR (4)     NOT NULL,
    [TaxStateRate]             DECIMAL (6, 4)  NOT NULL,
    [TaxCountyRate]            DECIMAL (6, 4)  NOT NULL,
    [TaxCityRate]              DECIMAL (6, 4)  NOT NULL,
    [TaxSpecialRate]           DECIMAL (6, 4)  NOT NULL,
    [TaxByZipID]               DECIMAL (10)    NOT NULL,
    [InvoiceNum]               DECIMAL (8)     NOT NULL,
    [ShipToPO]                 VARCHAR (40)    NOT NULL,
    [Form4473]                 DECIMAL (8)     NOT NULL,
    [CalcTax]                  VARCHAR (1)     NULL,
    [CreatedBy]                VARCHAR (4)     NULL,
    [CreatedDate]              DATETIME        NULL,
    [ChangedBy]                VARCHAR (4)     NULL,
    [ChangedDate]              DATETIME        NULL,
    [Version]                  VARCHAR (15)    NULL,
    [ForceTax]                 VARCHAR (1)     NULL,
    [NoPLPrint]                VARCHAR (1)     NULL,
    [ReleaseDate]              DATETIME        NULL,
    [SAddress]                 VARCHAR (35)    NULL,
    [SAddress2]                VARCHAR (35)    NULL,
    [SCity]                    VARCHAR (30)    NULL,
    [SState]                   VARCHAR (2)     NULL,
    [SZip]                     VARCHAR (10)    NULL,
    [SCountry]                 VARCHAR (2)     NULL,
    [ExternalOrderType]        VARCHAR (1)     NULL,
    [ExternalOrdNum]           BIGINT          NULL,
    [CCToken]                  VARCHAR (25)    NOT NULL,
    [CCApprovalCode]           VARCHAR (25)    NULL,
    [NoTaxChange]              VARCHAR (1)     NULL,
    [CCRetRef]                 VARCHAR (25)    NULL,
    [Sub_Labor]                NUMERIC (10, 2) NULL,
    [Sub_LaborRepair]          NUMERIC (10, 2) NULL,
    [Sub_Apparel]              NUMERIC (10, 2) NULL,
    [CouponDiscount]           NUMERIC (6, 2)  NULL,
    [ReadyToShip]              VARCHAR (4)     NULL,
    [PostType]                 VARCHAR (2)     NULL,
    [ShipDestinationType]      VARCHAR (1)     NULL,
    [ShipUPS]                  VARCHAR (1)     NULL,
    [IAS_Sub]                  NUMERIC (10, 2) NULL,
    [IAS_Disc]                 NUMERIC (10, 2) NULL,
    [IAS_Post]                 NUMERIC (10, 2) NULL,
    [IAS_Tax]                  NUMERIC (10, 2) NULL,
    [IAS_OTotal]               NUMERIC (10, 2) NULL,
    [IAS_Sub_Taxable]          NUMERIC (10, 2) NULL,
    [IAS_Sub_Labor]            NUMERIC (10, 2) NULL,
    [IAS_Sub_LaborRepair]      NUMERIC (10, 2) NULL,
    [IAS_Sub_Apparel]          NUMERIC (10, 2) NULL,
    [NumberOfCartons]          SMALLINT        NULL,
    [Packed]                   VARCHAR (4)     NOT NULL,
    [ShipLocation]             VARCHAR (1)     NULL,
    [CustApproval]             VARCHAR (1)     NULL,
    [MgrApproval]              VARCHAR (1)     NULL,
    [ReadyToShipDate]          DATETIME        NOT NULL,
    [CancelAfter]              DATETIME        NULL,
    [AuthorizedAmount]         NUMERIC (10, 2) NOT NULL,
    [AVSResult]                VARCHAR (1)     NULL,
    [CCTranStatus]             VARCHAR (1)     NULL,
    [CCLatestTransID]          VARCHAR (25)    NULL,
    [AdultSig]                 VARCHAR (1)     NULL,
    [CustomerSelectedPostType] VARCHAR (1)     NULL,
    [FreightTax]               NUMERIC (6, 4)  NULL,
    [NFAStamp]                 CHAR (1)        NOT NULL,
    [ChangeTime]               DATETIME2 (7)   NOT NULL,
    [ChangeUser]               NVARCHAR (128)  NULL,
    [HostName]                 NVARCHAR (128)  NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [OrderHeaderHistory_INDEX02]
    ON [dbo].[OrderHeaderHistory]([ChangeTime] DESC, [ORDNUM] ASC, [ID] ASC) WITH (FILLFACTOR = 100);


GO
CREATE NONCLUSTERED INDEX [OrderHeaderHistory_Index03]
    ON [dbo].[OrderHeaderHistory]([ORDNUM] ASC, [ChangeTime] DESC, [ID] ASC) WITH (FILLFACTOR = 100);


GO
ALTER TABLE [dbo].[OrderHeaderHistory]
    ADD CONSTRAINT [OrderHeaderHistory_INDEX01] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 100);


