CREATE TABLE [dbo].[POVendor] (
    [Recnum]         BIGINT        IDENTITY (1, 1) NOT NULL,
    [VENDOR_ID]      VARCHAR (8)   DEFAULT (' ') NOT NULL,
    [VENDOR_NAME]    VARCHAR (30)  DEFAULT (' ') NOT NULL,
    [VENDOR_ADDRESS] VARCHAR (30)  DEFAULT (' ') NOT NULL,
    [VENDOR_ADDR2]   VARCHAR (30)  DEFAULT (' ') NOT NULL,
    [VENDOR_CITY]    VARCHAR (20)  DEFAULT (' ') NOT NULL,
    [VENDOR_STATE]   VARCHAR (2)   DEFAULT (' ') NOT NULL,
    [VENDOR_ZIP]     VARCHAR (10)  DEFAULT (' ') NOT NULL,
    [VENDOR_PHONE]   VARCHAR (13)  DEFAULT (' ') NOT NULL,
    [VENDOR_TERMS]   DECIMAL (4)   DEFAULT ((0)) NOT NULL,
    [INTERNAT]       VARCHAR (1)   DEFAULT (' ') NOT NULL,
    [FFL_#]          VARCHAR (10)  DEFAULT (' ') NOT NULL,
    [VENDOR_PHONE2]  VARCHAR (13)  DEFAULT (' ') NOT NULL,
    [VENDOR_FAX]     VARCHAR (13)  DEFAULT (' ') NOT NULL,
    [CONTACT_NAME]   VARCHAR (30)  DEFAULT (' ') NOT NULL,
    [ACCOUNT_#]      VARCHAR (15)  DEFAULT (' ') NOT NULL,
    [TERMS_DESC]     VARCHAR (15)  DEFAULT (' ') NOT NULL,
    [NOTES1]         VARCHAR (35)  DEFAULT (' ') NOT NULL,
    [NOTES2]         VARCHAR (35)  DEFAULT (' ') NOT NULL,
    [NOTES3]         VARCHAR (35)  DEFAULT (' ') NOT NULL,
    [NOTES4]         VARCHAR (35)  DEFAULT (' ') NOT NULL,
    [NOTES5]         VARCHAR (35)  DEFAULT (' ') NOT NULL,
    [Country]        VARCHAR (2)   DEFAULT (' ') NOT NULL,
    [Notes]          VARCHAR (MAX) NULL,
    [CreatedBy]      VARCHAR (4)   DEFAULT (' ') NOT NULL,
    [CreatedDate]    DATETIME      DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]      VARCHAR (4)   DEFAULT (' ') NOT NULL,
    [ChangedDate]    DATETIME      DEFAULT ('01/01/1753') NOT NULL,
    [Version]        VARCHAR (15)  DEFAULT (' ') NOT NULL,
    [Email]          VARCHAR (100) DEFAULT (' ') NOT NULL,
    [APVendorID]     VARCHAR (8)   NULL,
    [INACTIVE_FLAG]  CHAR (1)      DEFAULT ('N') NULL,	
    CONSTRAINT [POVendor_INDEX01] PRIMARY KEY CLUSTERED ([VENDOR_ID] ASC) WITH (FILLFACTOR = 70)
);


GO
ALTER TABLE [dbo].[POVendor] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);




GO
CREATE UNIQUE NONCLUSTERED INDEX [POVendor_INDEX00]
    ON [dbo].[POVendor]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [POVendor_INDEX02]
    ON [dbo].[POVendor]([VENDOR_NAME] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

