CREATE TABLE [dbo].[CMASGRP] (
    [Recnum]      BIGINT       IDENTITY (1, 1) NOT NULL,
    [GROUP_CODE]  VARCHAR (10) DEFAULT (' ') NOT NULL,
    [DESCRIPTION] VARCHAR (30) DEFAULT (' ') NOT NULL,
    CONSTRAINT [CMASGRP_INDEX01] PRIMARY KEY CLUSTERED ([GROUP_CODE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CMASGRP_INDEX00]
    ON [dbo].[CMASGRP]([Recnum] ASC) WITH (FILLFACTOR = 70);

