CREATE TABLE [dbo].[INPRTGRP] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [CODE]        VARCHAR (6)     DEFAULT (' ') NOT NULL,
    [DESCRIPTION] VARCHAR (30)    DEFAULT (' ') NOT NULL,
    [TYPE_CODE]   VARCHAR (1)     DEFAULT (' ') NOT NULL,
    [COST_STD]    DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [COST_ACT]    DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [COST_TOTAL]  DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [COG_STD]     DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [COG_ACT]     DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [WIP_TOTAL]   DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [RAW_STD]     DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    [RAW_ACT]     DECIMAL (12, 4) DEFAULT ((0)) NOT NULL,
    CONSTRAINT [INPRTGRP_INDEX01] PRIMARY KEY CLUSTERED ([CODE] ASC) WITH (FILLFACTOR = 70)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INPRTGRP_INDEX00]
    ON [dbo].[INPRTGRP]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [INPRTGRP_INDEX02]
    ON [dbo].[INPRTGRP]([TYPE_CODE] ASC, [CODE] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);

