CREATE TABLE [dbo].[FEDBOOK] (
    [Recnum]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [GUNTYPE]     VARCHAR (1)     CONSTRAINT [DF__FEDBOOK__GUNTYPE__159C0B84] DEFAULT (' ') NOT NULL,
    [SERIAL]      VARCHAR (14)    CONSTRAINT [DF__FEDBOOK__SERIAL__16902FBD] DEFAULT (' ') NOT NULL,
    [RECEIVED]    DATETIME        CONSTRAINT [DF__FEDBOOK__RECEIVE__178453F6] DEFAULT ('01/01/1753') NOT NULL,
    [MANUFACT]    VARCHAR (10)    CONSTRAINT [DF__FEDBOOK__MANUFAC__1878782F] DEFAULT (' ') NOT NULL,
    [MODEL]       VARCHAR (10)    CONSTRAINT [DF__FEDBOOK__MODEL__196C9C68] DEFAULT (' ') NOT NULL,
    [SEMIFULL]    VARCHAR (1)     CONSTRAINT [DF__FEDBOOK__SEMIFUL__1A60C0A1] DEFAULT (' ') NOT NULL,
    [NAME]        VARCHAR (25)    CONSTRAINT [DF__FEDBOOK__NAME__1B54E4DA] DEFAULT (' ') NOT NULL,
    [STREET]      VARCHAR (20)    CONSTRAINT [DF__FEDBOOK__STREET__1C490913] DEFAULT (' ') NOT NULL,
    [CITY]        VARCHAR (15)    CONSTRAINT [DF__FEDBOOK__CITY__1D3D2D4C] DEFAULT (' ') NOT NULL,
    [STATE]       VARCHAR (2)     CONSTRAINT [DF__FEDBOOK__STATE__1E315185] DEFAULT (' ') NOT NULL,
    [SPRNUM]      VARCHAR (20)    CONSTRAINT [DF__FEDBOOK__SPRNUM__1F2575BE] DEFAULT (' ') NOT NULL,
    [GUNMODEL]    VARCHAR (20)    CONSTRAINT [DF__FEDBOOK__GUNMODE__201999F7] DEFAULT (' ') NOT NULL,
    [SOLD]        DATETIME        CONSTRAINT [DF__FEDBOOK__SOLD__210DBE30] DEFAULT ('01/01/1753') NOT NULL,
    [SONAME]      VARCHAR (25)    CONSTRAINT [DF__FEDBOOK__SONAME__2201E269] DEFAULT (' ') NOT NULL,
    [SOSTREET]    VARCHAR (35)    CONSTRAINT [DF__FEDBOOK__SOSTREE__22F606A2] DEFAULT (' ') NOT NULL,
    [SOCITY]      VARCHAR (15)    CONSTRAINT [DF__FEDBOOK__SOCITY__23EA2ADB] DEFAULT (' ') NOT NULL,
    [SOSTATE]     VARCHAR (2)     CONSTRAINT [DF__FEDBOOK__SOSTATE__24DE4F14] DEFAULT (' ') NOT NULL,
    [SOLDFFL]     VARCHAR (10)    CONSTRAINT [DF__FEDBOOK__SOLDFFL__25D2734D] DEFAULT (' ') NOT NULL,
    [ORDNUM]      DECIMAL (10, 2) CONSTRAINT [DF__FEDBOOK__ORDNUM__26C69786] DEFAULT ((0)) NOT NULL,
    [TAG]         VARCHAR (6)     CONSTRAINT [DF__FEDBOOK__TAG__27BABBBF] DEFAULT (' ') NOT NULL,
    [SAFETY]      VARCHAR (1)     CONSTRAINT [DF__FEDBOOK__SAFETY__28AEDFF8] DEFAULT (' ') NOT NULL,
    [GUNSMITH]    VARCHAR (10)    CONSTRAINT [DF__FEDBOOK__GUNSMIT__29A30431] DEFAULT (' ') NOT NULL,
    [TAGNUM]      DECIMAL (6)     CONSTRAINT [DF__FEDBOOK__TAGNUM__2A97286A] DEFAULT ((0)) NOT NULL,
    [FEDCODE]     VARCHAR (1)     CONSTRAINT [DF__FEDBOOK__FEDCODE__2B8B4CA3] DEFAULT (' ') NOT NULL,
    [CALIBER]     VARCHAR (10)    CONSTRAINT [DF__FEDBOOK__CALIBER__2C7F70DC] DEFAULT (' ') NOT NULL,
    [WO_NUMBER]   DECIMAL (6)     CONSTRAINT [DF__FEDBOOK__WO_NUMB__2D739515] DEFAULT ((0)) NOT NULL,
    [COMMENT]     VARCHAR (20)    CONSTRAINT [DF__FEDBOOK__COMMENT__2E67B94E] DEFAULT (' ') NOT NULL,
    [RCTICKET]    DECIMAL (6)     CONSTRAINT [DF__FEDBOOK__RCTICKE__2F5BDD87] DEFAULT ((0)) NOT NULL,
    [BAN_STATUS]  VARCHAR (1)     CONSTRAINT [DF__FEDBOOK__BAN_STA__305001C0] DEFAULT (' ') NOT NULL,
    [LOCATION]    VARCHAR (20)    CONSTRAINT [DF__FEDBOOK__LOCATIO__314425F9] DEFAULT (' ') NOT NULL,
    [CHANGE_FLAG] VARCHAR (1)     CONSTRAINT [DF__FEDBOOK__CHANGE___32384A32] DEFAULT (' ') NOT NULL,
    [INITIALS]    VARCHAR (10)    CONSTRAINT [DF__FEDBOOK__INITIAL__332C6E6B] DEFAULT (' ') NOT NULL,
    [NOTES]       VARCHAR (60)    CONSTRAINT [DF__FEDBOOK__NOTES__342092A4] DEFAULT (' ') NOT NULL,
    [CreatedBy]   VARCHAR (4)     CONSTRAINT [DF__FEDBOOK__Created__3514B6DD] DEFAULT (' ') NOT NULL,
    [CreatedDate] DATETIME        CONSTRAINT [DF__FEDBOOK__Created__3608DB16] DEFAULT ('01/01/1753') NOT NULL,
    [ChangedBy]   VARCHAR (4)     CONSTRAINT [DF__FEDBOOK__Changed__36FCFF4F] DEFAULT (' ') NOT NULL,
    [ChangedDate] DATETIME        CONSTRAINT [DF__FEDBOOK__Changed__37F12388] DEFAULT ('01/01/1753') NOT NULL,
    [Version]     VARCHAR (15)    CONSTRAINT [DF__FEDBOOK__Version__38E547C1] DEFAULT (' ') NOT NULL,
    [OrderSeq]    DECIMAL (8)     CONSTRAINT [DF__FEDBOOK__OrderSe__39D96BFA] DEFAULT ((0)) NOT NULL,
    [Form4473]    INT             NULL,
    [Recall]      VARCHAR (20)    NULL,
    [RMA]         INT             NULL,
    [LineNum]     INT             CONSTRAINT [DF_FEDBOOK_LineNum] DEFAULT ((0)) NOT NULL,
    [Headspace]   NUMERIC (4, 3)  CONSTRAINT [DF_FEDBOOK_Headspace] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [FEDBOOK_INDEX01] PRIMARY KEY CLUSTERED ([GUNTYPE] ASC, [SERIAL] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70)
);






GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX00]
    ON [dbo].[FEDBOOK]([Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX02]
    ON [dbo].[FEDBOOK]([ORDNUM] ASC, [LineNum] ASC, [GUNTYPE] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX03]
    ON [dbo].[FEDBOOK]([TAGNUM] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX04]
    ON [dbo].[FEDBOOK]([RCTICKET] ASC, [SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX05]
    ON [dbo].[FEDBOOK]([SONAME] ASC, [GUNTYPE] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX06]
    ON [dbo].[FEDBOOK]([SPRNUM] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX07]
    ON [dbo].[FEDBOOK]([GUNTYPE] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX08]
    ON [dbo].[FEDBOOK]([SERIAL] ASC, [RECEIVED] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX09]
    ON [dbo].[FEDBOOK]([GUNTYPE] ASC, [SOLD] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX11]
    ON [dbo].[FEDBOOK]([NAME] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX12]
    ON [dbo].[FEDBOOK]([ORDNUM] ASC, [LineNum] ASC, [SPRNUM] ASC, [OrderSeq] ASC, [Recnum] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX13]
    ON [dbo].[FEDBOOK]([WO_NUMBER] ASC, [SERIAL] ASC, [Recnum] ASC) WITH (FILLFACTOR = 70);


GO
CREATE UNIQUE NONCLUSTERED INDEX [FEDBOOK_INDEX14]
    ON [dbo].[FEDBOOK]([ORDNUM] ASC, [LineNum] ASC, [SERIAL] ASC, [OrderSeq] ASC, [Recnum] ASC);

