CREATE TABLE [stage].[CMASGRP] (
    [ID]                   BIGINT       IDENTITY (1, 1) NOT NULL,
    [Recnum]               BIGINT       NULL,
    [GROUP_CODE]           VARCHAR (10) NULL,
    [DESCRIPTION]          VARCHAR (30) NULL,
    [SYS_CHANGE_OPERATION] NCHAR (1)    NOT NULL,
    [SYS_CHANGE_VERSION]   BIGINT       NOT NULL,
    CONSTRAINT [pk_CMASGRP] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [CMASGRP_INDEX00]
    ON [stage].[CMASGRP]([GROUP_CODE] ASC);

