CREATE PROCEDURE [dbo].[sasp_QuantityAllocatedForPartOnReleasedOrders] 
(
@sPartNum VARCHAR(20)
)
AS
  DECLARE @PartNum VARCHAR(20);
  SELECT @PartNum = @sPartNum;
  SELECT SUM(MASTERLN.QUANS-MASTERLN.QUANSHIP)
  FROM MASTERLN
    INNER JOIN CUSTINFO 
      ON MASTERLN.ORDNUM = CUSTINFO.ORDNUM 
  WHERE MASTERLN.SPRNUM = @PartNum
    AND MASTERLN.QUAN > 0 
    AND LEFT(CUSTINFO.[STATUS],1) = 'R'
