CREATE PROCEDURE [dbo].[sasp_QuantityAllocatedForPartOnOrders] 
(
@sPartNum VARCHAR(20)
)
AS
  DECLARE @PartNum VARCHAR(20);
  SELECT @PartNum = @sPartNum;
  SELECT SUM(MASTERLN.QUAN-MASTERLN.QUANSHIP)
  FROM MASTERLN
    INNER JOIN CUSTINFO 
      ON MASTERLN.ORDNUM = CUSTINFO.ORDNUM 
  WHERE MASTERLN.SPRNUM = @PartNum
    AND MASTERLN.QUAN > 0 
    AND CUSTINFO.[STATUS] <> 'CN'
    AND LEFT(CUSTINFO.STATUS,1) <> 'S' 
    AND LEFT(CUSTINFO.STATUS,1) <> 'R'
